#!/usr/bin/env python3
"""NIST PKITS (v1.0.1) against SPARKTLS's x509_validate.

Test definitions come from BoringSSL's pki/testdata/nist-pkits/
pkits_testcases-inl.h (generated by BoringSSL from PKITS.pdf); the
certificates and CRLs are the NIST originals in certs/ and crls/ next to
it. Each test lists its certificates (trust anchor first, end entity
last) and the CRLs that must be consulted; PKITS requires revocation
status to be DETERMINED for every certificate on the path, hence
--crl-mode hard.

Usage: pkits_runner.py <pkits-dir> <validator> [--section 4.14] [--expected FILE] [--crl-mode hard|soft]
Exit 0 when no test outside the expected-failures list fails.
"""
import base64, os, re, subprocess, sys, tempfile

def parse_header(path):
    text = open(path).read()
    tests = []
    for m in re.finditer(
        r"//\s*(?P<num>\d+\.\d+\.\d+)\s+(?P<title>[^\n]*)\n.*?"
        r"certs\[\]\s*=\s*\{(?P<certs>[^}]*)\}.*?"
        r"crls\[\]\s*=\s*\{(?P<crls>[^}]*)\}.*?"
        r"info\.should_validate\s*=\s*(?P<ok>true|false)",
        text, re.S):
        certs = re.findall(r'"([^"]+)"', m.group("certs"))
        crls = re.findall(r'"([^"]+)"', m.group("crls"))
        tests.append((m.group("num"), m.group("title").strip(), certs, crls,
                      m.group("ok") == "true"))
    return tests

def pem(der, label):
    b = base64.encodebytes(der).decode().replace("\n", "")
    lines = [b[i:i+64] for i in range(0, len(b), 64)]
    return f"-----BEGIN {label}-----\n" + "\n".join(lines) + f"\n-----END {label}-----\n"

def main():
    args = sys.argv[1:]
    if len(args) < 2:
        print(__doc__); sys.exit(2)
    pkits, validator = args[0], args[1]
    section = None; expected_file = None; crl_mode = "hard"
    i = 2
    while i < len(args):
        if args[i] == "--section": section = args[i+1]; i += 2
        elif args[i] == "--expected": expected_file = args[i+1]; i += 2
        elif args[i] == "--crl-mode": crl_mode = args[i+1]; i += 2
        else: i += 1
    expected_fail = set()
    if expected_file and os.path.exists(expected_file):
        expected_fail = {l.strip() for l in open(expected_file) if l.strip() and not l.startswith("#")}

    tests = parse_header(os.path.join(pkits, "pkits_testcases-inl.h"))
    if section:
        tests = [t for t in tests if t[0].startswith(section + ".")]
    passed = failed = 0; failures = []; unexpected = []; fixed = []
    with tempfile.TemporaryDirectory() as tmp:
        for num, title, certs, crls, should in tests:
            ders = [open(os.path.join(pkits, "certs", c + ".crt"), "rb").read() for c in certs]
            trust = os.path.join(tmp, "trust.pem"); open(trust, "w").write(pem(ders[0], "CERTIFICATE"))
            peer = os.path.join(tmp, "peer.pem"); open(peer, "w").write(pem(ders[-1], "CERTIFICATE"))
            cmd = [validator, peer, trust]
            if len(ders) > 2:
                ints = os.path.join(tmp, "ints.pem")
                open(ints, "w").write("".join(pem(d, "CERTIFICATE") for d in ders[1:-1]))
                cmd.append(ints)
            cmd += ["--mode", "rfc5280", "--crl-mode", crl_mode]
            for c in crls:
                cmd += ["--crl", os.path.join(pkits, "crls", c + ".crl")]
            try:
                r = subprocess.run(cmd, capture_output=True, timeout=20)
                actual = r.returncode == 0
                err = r.returncode == 2
            except subprocess.TimeoutExpired:
                actual, err = None, True
            ok = (actual == should) and not err
            key = f"{num} {title}"
            if ok:
                passed += 1
                if key in expected_fail: fixed.append(key)
            else:
                failed += 1; failures.append(key)
                if key not in expected_fail: unexpected.append(key)
    print(f"=== PKITS: {passed}/{passed+failed} passed, {failed} failed ===")
    for f in failures:
        tag = "  (expected)" if f in expected_fail else ""
        print(f"  FAIL: {f}{tag}")
    if fixed:
        print(f"newly PASSING ({len(fixed)}), remove from the expected list:")
        for f in fixed: print(f"  {f}")
    if unexpected:
        print(f"!!! REGRESSION: {len(unexpected)} unexpected failure(s):")
        for f in unexpected: print(f"  {f}")
        sys.exit(1)
    sys.exit(0)

if __name__ == "__main__":
    main()
