#!/bin/bash
# Run x509-limbo certificate validation tests against SPARKTLS.
#
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$DIR/../.."
GEN_DIR="$DIR/generated"
VALIDATOR="$REPO_ROOT/bin/tests/x509_validate"
export ALR_NON_INTERACTIVE=1
export NO_COLOR=1

if [ ! -d "$GEN_DIR" ] || [ ! -f "$GEN_DIR/manifest.txt" ]; then
    echo "x509-limbo test cases not found; downloading/generating them now..."
    bash "$DIR/generate.sh"
fi

if [ ! -f "$VALIDATOR" ]; then
    echo "Validator not found; building it now..."
    cd "$REPO_ROOT"
    alr -n --no-tty exec -- gprbuild -q -P tests/x509/x509_validate.gpr
fi

echo "=== x509-limbo Certificate Validation Tests ==="
cat "$GEN_DIR/manifest.txt"
echo ""

PASS=0
FAIL=0
ERRORS=0
FIRST_FAILURES=""
FAILED_NAMES=$(mktemp)

for tc_dir in "$GEN_DIR"/*/; do
    [ -f "$tc_dir/expect.txt" ] || continue

    expected=$(cat "$tc_dir/expect.txt" | tr -d '\n')
    hostname=$(grep "^hostname=" "$tc_dir/meta.txt" | cut -d= -f2)
    vtime=$(grep "^time=" "$tc_dir/meta.txt" | cut -d= -f2)
    mode=$(grep "^mode=" "$tc_dir/meta.txt" 2>/dev/null | cut -d= -f2)
    tc_name=$(basename "$tc_dir")

    # Build command
    cmd=("$VALIDATOR" "$tc_dir/peer.pem" "$tc_dir/trust.pem")
    [ -f "$tc_dir/intermediates.pem" ] && cmd+=("$tc_dir/intermediates.pem")
    [ -n "$hostname" ] && cmd+=(--hostname "$hostname")
    [ -n "$vtime" ] && cmd+=(--time "$vtime")
    [ "$mode" = "rfc5280" ] && cmd+=(--mode rfc5280)
    #  CRL cases: x509-limbo semantics = soft on inapplicable CRLs,
    #  reject on revoked or invalid ones.
    for crl in "$tc_dir"/crl_*.pem; do
        [ -f "$crl" ] && cmd+=(--crl "$crl" --crl-mode soft)
    done

    # Run
    if timeout 10 "${cmd[@]}" > /dev/null 2>&1; then
        actual="SUCCESS"
    else
        rc=$?
        if [ $rc -eq 1 ]; then
            actual="FAILURE"
        else
            actual="ERROR"
            ERRORS=$((ERRORS + 1))
            continue
        fi
    fi

    if [ "$actual" = "$expected" ]; then
        PASS=$((PASS + 1))
    else
        FAIL=$((FAIL + 1))
        echo "$tc_name" >> "$FAILED_NAMES"
        if [ $FAIL -le 20 ]; then
            FIRST_FAILURES="$FIRST_FAILURES  FAIL: $tc_name expected=$expected got=$actual\n"
        fi
    fi

    # Progress
    TOTAL=$((PASS + FAIL))
    if [ $((TOTAL % 500)) -eq 0 ]; then
        echo "  ... $TOTAL tests (pass=$PASS fail=$FAIL errors=$ERRORS)"
    fi
done

TOTAL=$((PASS + FAIL))
echo ""

#  Regression detection by diff against EXPECTED_FAILURES.txt, the same
#  way tests/bogo does it: a count cannot tell one fixed case from one
#  broken case. Names are the x509-limbo test ids. --update-baseline
#  rewrites the list from this run (document why in git).
BASELINE="$DIR/EXPECTED_FAILURES.txt"
sort -u "$FAILED_NAMES" > "$FAILED_NAMES.sorted"
if [ "${1:-}" = "--update-baseline" ]; then
    { echo "# x509-limbo expected failures (test ids), one per line. Regenerated by"
      echo "# tests/x509/run.sh --update-baseline on $(date -u +%Y-%m-%d); document every change in git."
      cat "$FAILED_NAMES.sorted"; } > "$BASELINE"
    echo "Baseline written: $FAIL entries -> $BASELINE"
fi
KNOWN=0; NEW_FAIL=""; NEW_PASS=""
if [ -f "$BASELINE" ]; then
    EXPECTED=$(mktemp); grep -v '^#' "$BASELINE" | grep -v '^[[:space:]]*$' | sort -u > "$EXPECTED"
    NEW_FAIL=$(comm -23 "$FAILED_NAMES.sorted" "$EXPECTED")
    NEW_PASS=$(comm -13 "$FAILED_NAMES.sorted" "$EXPECTED")
    KNOWN=$(comm -12 "$FAILED_NAMES.sorted" "$EXPECTED" | wc -l)
    rm -f "$EXPECTED"
fi
UNEXPECTED=$((FAIL - KNOWN))
if [ -n "$NEW_FAIL" ]; then
    echo "!!! REGRESSION: $(echo "$NEW_FAIL" | wc -l) case(s) newly FAILING:"
    echo "$NEW_FAIL" | sed 's/^/    /'
elif [ -n "$FIRST_FAILURES" ] && [ ! -f "$BASELINE" ]; then
    echo "First failures (no EXPECTED_FAILURES.txt to diff against):"
    echo -e "$FIRST_FAILURES"
fi
if [ -n "$NEW_PASS" ]; then
    echo ">>> $(echo "$NEW_PASS" | wc -l) case(s) newly PASSING (update the baseline):"
    echo "$NEW_PASS" | sed 's/^/    /'
    echo "    Refresh with: tests/x509/run.sh --update-baseline"
fi
rm -f "$FAILED_NAMES" "$FAILED_NAMES.sorted"
echo "=== x509-limbo: $PASS/$TOTAL passed, $UNEXPECTED failed, $KNOWN known, $ERRORS errors ==="
#  Without a baseline every failure counts.
[ -z "$NEW_FAIL" ] && [ $ERRORS -eq 0 ] && { [ -f "$BASELINE" ] || [ $FAIL -eq 0 ]; } && exit 0 || exit 1
