name = "sparktls"
description = "SPARK implementation of TLS 1.3"
version = "0.0.0"

authors = ["Jon Andrew"]
maintainers = ["Jon Andrew <jonfandrew@fastmail.com>"]
maintainers-logins = ["docandrew"]
[[depends-on]]
gnatprove = "^12.1.1"
[[depends-on]]
gnat = "^13.1.0"
[[depends-on]]
sparknacl = "^4.0.0"
[[depends-on]]
sparkx509 = "~0.0.1"
[[pins]]
sparkx509 = { path='../sparkx509' }
