--  SPARKTLS Fiat P-256 — Faithful port of fiat-crypto p256_64.c
--
--  Original: https://github.com/mit-plv/fiat-crypto
--  Generated by: 'src/ExtractionOCaml/word_by_word_montgomery' --inline
--    --static --use-value-barrier p256 64 '2^256 - 2^224 + 2^192 + 2^96 - 1'
--
--  Every function is a line-by-line translation of the Coq-verified C output.
--  The SSA form is preserved for performance (optimal register allocation).

with Interfaces; use Interfaces;

package body SPARKTLS.Fiat_P256 with
   SPARK_Mode => On
is
   Mask64 : constant Unsigned_128 := 16#FFFF_FFFF_FFFF_FFFF#;


function Mul (Arg1, Arg2 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8          : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16    : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24   : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32   : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40   : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48   : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56   : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64   : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72   : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80   : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88   : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96   : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170, x171, x172, x173, x174, x175, x176 : Unsigned_64;
   x177, x178, x179, x180, x181, x182, x183, x184 : Unsigned_64;
   x185, x186, x187 : Unsigned_64;
begin
   x1 := Arg1(1);
   x2 := Arg1(2);
   x3 := Arg1(3);
   x4 := Arg1(0);

   -- iteration 1: arg1[0] * arg2
   declare
      T_5 : constant Unsigned_128 := Unsigned_128(x4) * Unsigned_128(Arg2(3));
   begin
      x5 := Unsigned_64(T_5 and 16#FFFF_FFFF_FFFF_FFFF#);
      x6 := Unsigned_64(Shift_Right(T_5, 64));
   end;
   declare
      T_7 : constant Unsigned_128 := Unsigned_128(x4) * Unsigned_128(Arg2(2));
   begin
      x7 := Unsigned_64(T_7 and 16#FFFF_FFFF_FFFF_FFFF#);
      x8 := Unsigned_64(Shift_Right(T_7, 64));
   end;
   declare
      T_9 : constant Unsigned_128 := Unsigned_128(x4) * Unsigned_128(Arg2(1));
   begin
      x9 := Unsigned_64(T_9 and 16#FFFF_FFFF_FFFF_FFFF#);
      x10 := Unsigned_64(Shift_Right(T_9, 64));
   end;
   declare
      T_11 : constant Unsigned_128 := Unsigned_128(x4) * Unsigned_128(Arg2(0));
   begin
      x11 := Unsigned_64(T_11 and 16#FFFF_FFFF_FFFF_FFFF#);
      x12 := Unsigned_64(Shift_Right(T_11, 64));
   end;
   declare
      T_13 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x12) + Unsigned_128(x9);
   begin
      x13 := Unsigned_64(T_13 and 16#FFFF_FFFF_FFFF_FFFF#);
      x14 := Unsigned_64(Shift_Right(T_13, 64));
   end;
   declare
      T_15 : constant Unsigned_128 := Unsigned_128(x14) + Unsigned_128(x10) + Unsigned_128(x7);
   begin
      x15 := Unsigned_64(T_15 and 16#FFFF_FFFF_FFFF_FFFF#);
      x16 := Unsigned_64(Shift_Right(T_15, 64));
   end;
   declare
      T_17 : constant Unsigned_128 := Unsigned_128(x16) + Unsigned_128(x8) + Unsigned_128(x5);
   begin
      x17 := Unsigned_64(T_17 and 16#FFFF_FFFF_FFFF_FFFF#);
      x18 := Unsigned_64(Shift_Right(T_17, 64));
   end;
   x19 := x18 + x6;

   -- Montgomery reduction, iteration 1
   declare
      T_20 : constant Unsigned_128 := Unsigned_128(x11) * Unsigned_128(16#FFFF_FFFF_0000_0001#);
   begin
      x20 := Unsigned_64(T_20 and 16#FFFF_FFFF_FFFF_FFFF#);
      x21 := Unsigned_64(Shift_Right(T_20, 64));
   end;
   declare
      T_22 : constant Unsigned_128 := Unsigned_128(x11) * Unsigned_128(16#0000_0000_FFFF_FFFF#);
   begin
      x22 := Unsigned_64(T_22 and 16#FFFF_FFFF_FFFF_FFFF#);
      x23 := Unsigned_64(Shift_Right(T_22, 64));
   end;
   declare
      T_24 : constant Unsigned_128 := Unsigned_128(x11) * Unsigned_128(16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x24 := Unsigned_64(T_24 and 16#FFFF_FFFF_FFFF_FFFF#);
      x25 := Unsigned_64(Shift_Right(T_24, 64));
   end;
   declare
      T_26 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x25) + Unsigned_128(x22);
   begin
      x26 := Unsigned_64(T_26 and 16#FFFF_FFFF_FFFF_FFFF#);
      x27 := Unsigned_64(Shift_Right(T_26, 64));
   end;
   x28 := x27 + x23;
   declare
      T_29 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x11) + Unsigned_128(x24);
   begin
      x29 := Unsigned_64(T_29 and 16#FFFF_FFFF_FFFF_FFFF#);
      x30 := Unsigned_64(Shift_Right(T_29, 64));
   end;
   declare
      T_31 : constant Unsigned_128 := Unsigned_128(x30) + Unsigned_128(x13) + Unsigned_128(x26);
   begin
      x31 := Unsigned_64(T_31 and 16#FFFF_FFFF_FFFF_FFFF#);
      x32 := Unsigned_64(Shift_Right(T_31, 64));
   end;
   declare
      T_33 : constant Unsigned_128 := Unsigned_128(x32) + Unsigned_128(x15) + Unsigned_128(x28);
   begin
      x33 := Unsigned_64(T_33 and 16#FFFF_FFFF_FFFF_FFFF#);
      x34 := Unsigned_64(Shift_Right(T_33, 64));
   end;
   declare
      T_35 : constant Unsigned_128 := Unsigned_128(x34) + Unsigned_128(x17) + Unsigned_128(x20);
   begin
      x35 := Unsigned_64(T_35 and 16#FFFF_FFFF_FFFF_FFFF#);
      x36 := Unsigned_64(Shift_Right(T_35, 64));
   end;
   declare
      T_37 : constant Unsigned_128 := Unsigned_128(x36) + Unsigned_128(x19) + Unsigned_128(x21);
   begin
      x37 := Unsigned_64(T_37 and 16#FFFF_FFFF_FFFF_FFFF#);
      x38 := Unsigned_64(Shift_Right(T_37, 64));
   end;

   -- iteration 2: arg1[1] * arg2
   declare
      T_39 : constant Unsigned_128 := Unsigned_128(x1) * Unsigned_128(Arg2(3));
   begin
      x39 := Unsigned_64(T_39 and 16#FFFF_FFFF_FFFF_FFFF#);
      x40 := Unsigned_64(Shift_Right(T_39, 64));
   end;
   declare
      T_41 : constant Unsigned_128 := Unsigned_128(x1) * Unsigned_128(Arg2(2));
   begin
      x41 := Unsigned_64(T_41 and 16#FFFF_FFFF_FFFF_FFFF#);
      x42 := Unsigned_64(Shift_Right(T_41, 64));
   end;
   declare
      T_43 : constant Unsigned_128 := Unsigned_128(x1) * Unsigned_128(Arg2(1));
   begin
      x43 := Unsigned_64(T_43 and 16#FFFF_FFFF_FFFF_FFFF#);
      x44 := Unsigned_64(Shift_Right(T_43, 64));
   end;
   declare
      T_45 : constant Unsigned_128 := Unsigned_128(x1) * Unsigned_128(Arg2(0));
   begin
      x45 := Unsigned_64(T_45 and 16#FFFF_FFFF_FFFF_FFFF#);
      x46 := Unsigned_64(Shift_Right(T_45, 64));
   end;
   declare
      T_47 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x46) + Unsigned_128(x43);
   begin
      x47 := Unsigned_64(T_47 and 16#FFFF_FFFF_FFFF_FFFF#);
      x48 := Unsigned_64(Shift_Right(T_47, 64));
   end;
   declare
      T_49 : constant Unsigned_128 := Unsigned_128(x48) + Unsigned_128(x44) + Unsigned_128(x41);
   begin
      x49 := Unsigned_64(T_49 and 16#FFFF_FFFF_FFFF_FFFF#);
      x50 := Unsigned_64(Shift_Right(T_49, 64));
   end;
   declare
      T_51 : constant Unsigned_128 := Unsigned_128(x50) + Unsigned_128(x42) + Unsigned_128(x39);
   begin
      x51 := Unsigned_64(T_51 and 16#FFFF_FFFF_FFFF_FFFF#);
      x52 := Unsigned_64(Shift_Right(T_51, 64));
   end;
   x53 := x52 + x40;
   declare
      T_54 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x31) + Unsigned_128(x45);
   begin
      x54 := Unsigned_64(T_54 and 16#FFFF_FFFF_FFFF_FFFF#);
      x55 := Unsigned_64(Shift_Right(T_54, 64));
   end;
   declare
      T_56 : constant Unsigned_128 := Unsigned_128(x55) + Unsigned_128(x33) + Unsigned_128(x47);
   begin
      x56 := Unsigned_64(T_56 and 16#FFFF_FFFF_FFFF_FFFF#);
      x57 := Unsigned_64(Shift_Right(T_56, 64));
   end;
   declare
      T_58 : constant Unsigned_128 := Unsigned_128(x57) + Unsigned_128(x35) + Unsigned_128(x49);
   begin
      x58 := Unsigned_64(T_58 and 16#FFFF_FFFF_FFFF_FFFF#);
      x59 := Unsigned_64(Shift_Right(T_58, 64));
   end;
   declare
      T_60 : constant Unsigned_128 := Unsigned_128(x59) + Unsigned_128(x37) + Unsigned_128(x51);
   begin
      x60 := Unsigned_64(T_60 and 16#FFFF_FFFF_FFFF_FFFF#);
      x61 := Unsigned_64(Shift_Right(T_60, 64));
   end;
   declare
      T_62 : constant Unsigned_128 := Unsigned_128(x61) + Unsigned_128(x38) + Unsigned_128(x53);
   begin
      x62 := Unsigned_64(T_62 and 16#FFFF_FFFF_FFFF_FFFF#);
      x63 := Unsigned_64(Shift_Right(T_62, 64));
   end;

   -- Montgomery reduction, iteration 2
   declare
      T_64 : constant Unsigned_128 := Unsigned_128(x54) * Unsigned_128(16#FFFF_FFFF_0000_0001#);
   begin
      x64 := Unsigned_64(T_64 and 16#FFFF_FFFF_FFFF_FFFF#);
      x65 := Unsigned_64(Shift_Right(T_64, 64));
   end;
   declare
      T_66 : constant Unsigned_128 := Unsigned_128(x54) * Unsigned_128(16#0000_0000_FFFF_FFFF#);
   begin
      x66 := Unsigned_64(T_66 and 16#FFFF_FFFF_FFFF_FFFF#);
      x67 := Unsigned_64(Shift_Right(T_66, 64));
   end;
   declare
      T_68 : constant Unsigned_128 := Unsigned_128(x54) * Unsigned_128(16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x68 := Unsigned_64(T_68 and 16#FFFF_FFFF_FFFF_FFFF#);
      x69 := Unsigned_64(Shift_Right(T_68, 64));
   end;
   declare
      T_70 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x69) + Unsigned_128(x66);
   begin
      x70 := Unsigned_64(T_70 and 16#FFFF_FFFF_FFFF_FFFF#);
      x71 := Unsigned_64(Shift_Right(T_70, 64));
   end;
   x72 := x71 + x67;
   declare
      T_73 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x54) + Unsigned_128(x68);
   begin
      x73 := Unsigned_64(T_73 and 16#FFFF_FFFF_FFFF_FFFF#);
      x74 := Unsigned_64(Shift_Right(T_73, 64));
   end;
   declare
      T_75 : constant Unsigned_128 := Unsigned_128(x74) + Unsigned_128(x56) + Unsigned_128(x70);
   begin
      x75 := Unsigned_64(T_75 and 16#FFFF_FFFF_FFFF_FFFF#);
      x76 := Unsigned_64(Shift_Right(T_75, 64));
   end;
   declare
      T_77 : constant Unsigned_128 := Unsigned_128(x76) + Unsigned_128(x58) + Unsigned_128(x72);
   begin
      x77 := Unsigned_64(T_77 and 16#FFFF_FFFF_FFFF_FFFF#);
      x78 := Unsigned_64(Shift_Right(T_77, 64));
   end;
   declare
      T_79 : constant Unsigned_128 := Unsigned_128(x78) + Unsigned_128(x60) + Unsigned_128(x64);
   begin
      x79 := Unsigned_64(T_79 and 16#FFFF_FFFF_FFFF_FFFF#);
      x80 := Unsigned_64(Shift_Right(T_79, 64));
   end;
   declare
      T_81 : constant Unsigned_128 := Unsigned_128(x80) + Unsigned_128(x62) + Unsigned_128(x65);
   begin
      x81 := Unsigned_64(T_81 and 16#FFFF_FFFF_FFFF_FFFF#);
      x82 := Unsigned_64(Shift_Right(T_81, 64));
   end;
   x83 := x82 + x63;

   -- iteration 3: arg1[2] * arg2
   declare
      T_84 : constant Unsigned_128 := Unsigned_128(x2) * Unsigned_128(Arg2(3));
   begin
      x84 := Unsigned_64(T_84 and 16#FFFF_FFFF_FFFF_FFFF#);
      x85 := Unsigned_64(Shift_Right(T_84, 64));
   end;
   declare
      T_86 : constant Unsigned_128 := Unsigned_128(x2) * Unsigned_128(Arg2(2));
   begin
      x86 := Unsigned_64(T_86 and 16#FFFF_FFFF_FFFF_FFFF#);
      x87 := Unsigned_64(Shift_Right(T_86, 64));
   end;
   declare
      T_88 : constant Unsigned_128 := Unsigned_128(x2) * Unsigned_128(Arg2(1));
   begin
      x88 := Unsigned_64(T_88 and 16#FFFF_FFFF_FFFF_FFFF#);
      x89 := Unsigned_64(Shift_Right(T_88, 64));
   end;
   declare
      T_90 : constant Unsigned_128 := Unsigned_128(x2) * Unsigned_128(Arg2(0));
   begin
      x90 := Unsigned_64(T_90 and 16#FFFF_FFFF_FFFF_FFFF#);
      x91 := Unsigned_64(Shift_Right(T_90, 64));
   end;
   declare
      T_92 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x91) + Unsigned_128(x88);
   begin
      x92 := Unsigned_64(T_92 and 16#FFFF_FFFF_FFFF_FFFF#);
      x93 := Unsigned_64(Shift_Right(T_92, 64));
   end;
   declare
      T_94 : constant Unsigned_128 := Unsigned_128(x93) + Unsigned_128(x89) + Unsigned_128(x86);
   begin
      x94 := Unsigned_64(T_94 and 16#FFFF_FFFF_FFFF_FFFF#);
      x95 := Unsigned_64(Shift_Right(T_94, 64));
   end;
   declare
      T_96 : constant Unsigned_128 := Unsigned_128(x95) + Unsigned_128(x87) + Unsigned_128(x84);
   begin
      x96 := Unsigned_64(T_96 and 16#FFFF_FFFF_FFFF_FFFF#);
      x97 := Unsigned_64(Shift_Right(T_96, 64));
   end;
   x98 := x97 + x85;
   declare
      T_99 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x75) + Unsigned_128(x90);
   begin
      x99 := Unsigned_64(T_99 and 16#FFFF_FFFF_FFFF_FFFF#);
      x100 := Unsigned_64(Shift_Right(T_99, 64));
   end;
   declare
      T_101 : constant Unsigned_128 := Unsigned_128(x100) + Unsigned_128(x77) + Unsigned_128(x92);
   begin
      x101 := Unsigned_64(T_101 and 16#FFFF_FFFF_FFFF_FFFF#);
      x102 := Unsigned_64(Shift_Right(T_101, 64));
   end;
   declare
      T_103 : constant Unsigned_128 := Unsigned_128(x102) + Unsigned_128(x79) + Unsigned_128(x94);
   begin
      x103 := Unsigned_64(T_103 and 16#FFFF_FFFF_FFFF_FFFF#);
      x104 := Unsigned_64(Shift_Right(T_103, 64));
   end;
   declare
      T_105 : constant Unsigned_128 := Unsigned_128(x104) + Unsigned_128(x81) + Unsigned_128(x96);
   begin
      x105 := Unsigned_64(T_105 and 16#FFFF_FFFF_FFFF_FFFF#);
      x106 := Unsigned_64(Shift_Right(T_105, 64));
   end;
   declare
      T_107 : constant Unsigned_128 := Unsigned_128(x106) + Unsigned_128(x83) + Unsigned_128(x98);
   begin
      x107 := Unsigned_64(T_107 and 16#FFFF_FFFF_FFFF_FFFF#);
      x108 := Unsigned_64(Shift_Right(T_107, 64));
   end;

   -- Montgomery reduction, iteration 3
   declare
      T_109 : constant Unsigned_128 := Unsigned_128(x99) * Unsigned_128(16#FFFF_FFFF_0000_0001#);
   begin
      x109 := Unsigned_64(T_109 and 16#FFFF_FFFF_FFFF_FFFF#);
      x110 := Unsigned_64(Shift_Right(T_109, 64));
   end;
   declare
      T_111 : constant Unsigned_128 := Unsigned_128(x99) * Unsigned_128(16#0000_0000_FFFF_FFFF#);
   begin
      x111 := Unsigned_64(T_111 and 16#FFFF_FFFF_FFFF_FFFF#);
      x112 := Unsigned_64(Shift_Right(T_111, 64));
   end;
   declare
      T_113 : constant Unsigned_128 := Unsigned_128(x99) * Unsigned_128(16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x113 := Unsigned_64(T_113 and 16#FFFF_FFFF_FFFF_FFFF#);
      x114 := Unsigned_64(Shift_Right(T_113, 64));
   end;
   declare
      T_115 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x114) + Unsigned_128(x111);
   begin
      x115 := Unsigned_64(T_115 and 16#FFFF_FFFF_FFFF_FFFF#);
      x116 := Unsigned_64(Shift_Right(T_115, 64));
   end;
   x117 := x116 + x112;
   declare
      T_118 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x99) + Unsigned_128(x113);
   begin
      x118 := Unsigned_64(T_118 and 16#FFFF_FFFF_FFFF_FFFF#);
      x119 := Unsigned_64(Shift_Right(T_118, 64));
   end;
   declare
      T_120 : constant Unsigned_128 := Unsigned_128(x119) + Unsigned_128(x101) + Unsigned_128(x115);
   begin
      x120 := Unsigned_64(T_120 and 16#FFFF_FFFF_FFFF_FFFF#);
      x121 := Unsigned_64(Shift_Right(T_120, 64));
   end;
   declare
      T_122 : constant Unsigned_128 := Unsigned_128(x121) + Unsigned_128(x103) + Unsigned_128(x117);
   begin
      x122 := Unsigned_64(T_122 and 16#FFFF_FFFF_FFFF_FFFF#);
      x123 := Unsigned_64(Shift_Right(T_122, 64));
   end;
   declare
      T_124 : constant Unsigned_128 := Unsigned_128(x123) + Unsigned_128(x105) + Unsigned_128(x109);
   begin
      x124 := Unsigned_64(T_124 and 16#FFFF_FFFF_FFFF_FFFF#);
      x125 := Unsigned_64(Shift_Right(T_124, 64));
   end;
   declare
      T_126 : constant Unsigned_128 := Unsigned_128(x125) + Unsigned_128(x107) + Unsigned_128(x110);
   begin
      x126 := Unsigned_64(T_126 and 16#FFFF_FFFF_FFFF_FFFF#);
      x127 := Unsigned_64(Shift_Right(T_126, 64));
   end;
   x128 := x127 + x108;

   -- iteration 4: arg1[3] * arg2
   declare
      T_129 : constant Unsigned_128 := Unsigned_128(x3) * Unsigned_128(Arg2(3));
   begin
      x129 := Unsigned_64(T_129 and 16#FFFF_FFFF_FFFF_FFFF#);
      x130 := Unsigned_64(Shift_Right(T_129, 64));
   end;
   declare
      T_131 : constant Unsigned_128 := Unsigned_128(x3) * Unsigned_128(Arg2(2));
   begin
      x131 := Unsigned_64(T_131 and 16#FFFF_FFFF_FFFF_FFFF#);
      x132 := Unsigned_64(Shift_Right(T_131, 64));
   end;
   declare
      T_133 : constant Unsigned_128 := Unsigned_128(x3) * Unsigned_128(Arg2(1));
   begin
      x133 := Unsigned_64(T_133 and 16#FFFF_FFFF_FFFF_FFFF#);
      x134 := Unsigned_64(Shift_Right(T_133, 64));
   end;
   declare
      T_135 : constant Unsigned_128 := Unsigned_128(x3) * Unsigned_128(Arg2(0));
   begin
      x135 := Unsigned_64(T_135 and 16#FFFF_FFFF_FFFF_FFFF#);
      x136 := Unsigned_64(Shift_Right(T_135, 64));
   end;
   declare
      T_137 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x136) + Unsigned_128(x133);
   begin
      x137 := Unsigned_64(T_137 and 16#FFFF_FFFF_FFFF_FFFF#);
      x138 := Unsigned_64(Shift_Right(T_137, 64));
   end;
   declare
      T_139 : constant Unsigned_128 := Unsigned_128(x138) + Unsigned_128(x134) + Unsigned_128(x131);
   begin
      x139 := Unsigned_64(T_139 and 16#FFFF_FFFF_FFFF_FFFF#);
      x140 := Unsigned_64(Shift_Right(T_139, 64));
   end;
   declare
      T_141 : constant Unsigned_128 := Unsigned_128(x140) + Unsigned_128(x132) + Unsigned_128(x129);
   begin
      x141 := Unsigned_64(T_141 and 16#FFFF_FFFF_FFFF_FFFF#);
      x142 := Unsigned_64(Shift_Right(T_141, 64));
   end;
   x143 := x142 + x130;
   declare
      T_144 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x120) + Unsigned_128(x135);
   begin
      x144 := Unsigned_64(T_144 and 16#FFFF_FFFF_FFFF_FFFF#);
      x145 := Unsigned_64(Shift_Right(T_144, 64));
   end;
   declare
      T_146 : constant Unsigned_128 := Unsigned_128(x145) + Unsigned_128(x122) + Unsigned_128(x137);
   begin
      x146 := Unsigned_64(T_146 and 16#FFFF_FFFF_FFFF_FFFF#);
      x147 := Unsigned_64(Shift_Right(T_146, 64));
   end;
   declare
      T_148 : constant Unsigned_128 := Unsigned_128(x147) + Unsigned_128(x124) + Unsigned_128(x139);
   begin
      x148 := Unsigned_64(T_148 and 16#FFFF_FFFF_FFFF_FFFF#);
      x149 := Unsigned_64(Shift_Right(T_148, 64));
   end;
   declare
      T_150 : constant Unsigned_128 := Unsigned_128(x149) + Unsigned_128(x126) + Unsigned_128(x141);
   begin
      x150 := Unsigned_64(T_150 and 16#FFFF_FFFF_FFFF_FFFF#);
      x151 := Unsigned_64(Shift_Right(T_150, 64));
   end;
   declare
      T_152 : constant Unsigned_128 := Unsigned_128(x151) + Unsigned_128(x128) + Unsigned_128(x143);
   begin
      x152 := Unsigned_64(T_152 and 16#FFFF_FFFF_FFFF_FFFF#);
      x153 := Unsigned_64(Shift_Right(T_152, 64));
   end;

   -- Montgomery reduction, iteration 4
   declare
      T_154 : constant Unsigned_128 := Unsigned_128(x144) * Unsigned_128(16#FFFF_FFFF_0000_0001#);
   begin
      x154 := Unsigned_64(T_154 and 16#FFFF_FFFF_FFFF_FFFF#);
      x155 := Unsigned_64(Shift_Right(T_154, 64));
   end;
   declare
      T_156 : constant Unsigned_128 := Unsigned_128(x144) * Unsigned_128(16#0000_0000_FFFF_FFFF#);
   begin
      x156 := Unsigned_64(T_156 and 16#FFFF_FFFF_FFFF_FFFF#);
      x157 := Unsigned_64(Shift_Right(T_156, 64));
   end;
   declare
      T_158 : constant Unsigned_128 := Unsigned_128(x144) * Unsigned_128(16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x158 := Unsigned_64(T_158 and 16#FFFF_FFFF_FFFF_FFFF#);
      x159 := Unsigned_64(Shift_Right(T_158, 64));
   end;
   declare
      T_160 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x159) + Unsigned_128(x156);
   begin
      x160 := Unsigned_64(T_160 and 16#FFFF_FFFF_FFFF_FFFF#);
      x161 := Unsigned_64(Shift_Right(T_160, 64));
   end;
   x162 := x161 + x157;
   declare
      T_163 : constant Unsigned_128 := Unsigned_128(0) + Unsigned_128(x144) + Unsigned_128(x158);
   begin
      x163 := Unsigned_64(T_163 and 16#FFFF_FFFF_FFFF_FFFF#);
      x164 := Unsigned_64(Shift_Right(T_163, 64));
   end;
   declare
      T_165 : constant Unsigned_128 := Unsigned_128(x164) + Unsigned_128(x146) + Unsigned_128(x160);
   begin
      x165 := Unsigned_64(T_165 and 16#FFFF_FFFF_FFFF_FFFF#);
      x166 := Unsigned_64(Shift_Right(T_165, 64));
   end;
   declare
      T_167 : constant Unsigned_128 := Unsigned_128(x166) + Unsigned_128(x148) + Unsigned_128(x162);
   begin
      x167 := Unsigned_64(T_167 and 16#FFFF_FFFF_FFFF_FFFF#);
      x168 := Unsigned_64(Shift_Right(T_167, 64));
   end;
   declare
      T_169 : constant Unsigned_128 := Unsigned_128(x168) + Unsigned_128(x150) + Unsigned_128(x154);
   begin
      x169 := Unsigned_64(T_169 and 16#FFFF_FFFF_FFFF_FFFF#);
      x170 := Unsigned_64(Shift_Right(T_169, 64));
   end;
   declare
      T_171 : constant Unsigned_128 := Unsigned_128(x170) + Unsigned_128(x152) + Unsigned_128(x155);
   begin
      x171 := Unsigned_64(T_171 and 16#FFFF_FFFF_FFFF_FFFF#);
      x172 := Unsigned_64(Shift_Right(T_171, 64));
   end;
   x173 := x172 + x153;

   -- final conditional subtraction
   declare
      T_174 : constant Unsigned_128 := Unsigned_128(x165) - Unsigned_128(0) - Unsigned_128(16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x174 := Unsigned_64(T_174 and 16#FFFF_FFFF_FFFF_FFFF#);
      x175 := Unsigned_64(Shift_Right(T_174, 64)) and 1;
   end;
   declare
      T_176 : constant Unsigned_128 := Unsigned_128(x167) - Unsigned_128(x175) - Unsigned_128(16#0000_0000_FFFF_FFFF#);
   begin
      x176 := Unsigned_64(T_176 and 16#FFFF_FFFF_FFFF_FFFF#);
      x177 := Unsigned_64(Shift_Right(T_176, 64)) and 1;
   end;
   declare
      T_178 : constant Unsigned_128 := Unsigned_128(x169) - Unsigned_128(x177) - Unsigned_128(0);
   begin
      x178 := Unsigned_64(T_178 and 16#FFFF_FFFF_FFFF_FFFF#);
      x179 := Unsigned_64(Shift_Right(T_178, 64)) and 1;
   end;
   declare
      T_180 : constant Unsigned_128 := Unsigned_128(x171) - Unsigned_128(x179) - Unsigned_128(16#FFFF_FFFF_0000_0001#);
   begin
      x180 := Unsigned_64(T_180 and 16#FFFF_FFFF_FFFF_FFFF#);
      x181 := Unsigned_64(Shift_Right(T_180, 64)) and 1;
   end;
   declare
      T_182 : constant Unsigned_128 := Unsigned_128(x173) - Unsigned_128(x181) - Unsigned_128(0);
   begin
      x182 := Unsigned_64(T_182 and 16#FFFF_FFFF_FFFF_FFFF#);
      x183 := Unsigned_64(Shift_Right(T_182, 64)) and 1;
   end;
   declare
      Mask_184 : constant Unsigned_64 := -(x183 and 1);
   begin
      x184 := (Mask_184 and x165) or ((not Mask_184) and x174);
   end;
   declare
      Mask_185 : constant Unsigned_64 := -(x183 and 1);
   begin
      x185 := (Mask_185 and x167) or ((not Mask_185) and x176);
   end;
   declare
      Mask_186 : constant Unsigned_64 := -(x183 and 1);
   begin
      x186 := (Mask_186 and x169) or ((not Mask_186) and x178);
   end;
   declare
      Mask_187 : constant Unsigned_64 := -(x183 and 1);
   begin
      x187 := (Mask_187 and x171) or ((not Mask_187) and x180);
   end;

   Out1 := (x184, x185, x186, x187);
   return Out1;
end Mul;

function Sqr (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8             : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16       : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24      : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32      : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40      : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48      : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56      : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64      : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72      : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80      : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88      : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96      : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170, x171, x172, x173, x174, x175, x176 : Unsigned_64;
   x177, x178, x179, x180, x181, x182, x183, x184 : Unsigned_64;
   x185, x186, x187                              : Unsigned_64;
begin
   -- Load arg1 limbs
   x1 := Arg1 (1);
   x2 := Arg1 (2);
   x3 := Arg1 (3);
   x4 := Arg1 (0);

   -- Round 1: multiply by x4 = arg1[0]
   declare T_5 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (Arg1 (3));
   begin x5 := Unsigned_64 (T_5 and 16#FFFF_FFFF_FFFF_FFFF#); x6 := Unsigned_64 (Shift_Right (T_5, 64)); end;
   declare T_7 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (Arg1 (2));
   begin x7 := Unsigned_64 (T_7 and 16#FFFF_FFFF_FFFF_FFFF#); x8 := Unsigned_64 (Shift_Right (T_7, 64)); end;
   declare T_9 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (Arg1 (1));
   begin x9 := Unsigned_64 (T_9 and 16#FFFF_FFFF_FFFF_FFFF#); x10 := Unsigned_64 (Shift_Right (T_9, 64)); end;
   declare T_11 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (Arg1 (0));
   begin x11 := Unsigned_64 (T_11 and 16#FFFF_FFFF_FFFF_FFFF#); x12 := Unsigned_64 (Shift_Right (T_11, 64)); end;

   declare T_13 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x12) + Unsigned_128 (x9);
   begin x13 := Unsigned_64 (T_13 and 16#FFFF_FFFF_FFFF_FFFF#); x14 := Unsigned_64 (Shift_Right (T_13, 64)); end;
   declare T_15 : constant Unsigned_128 := Unsigned_128 (x14) + Unsigned_128 (x10) + Unsigned_128 (x7);
   begin x15 := Unsigned_64 (T_15 and 16#FFFF_FFFF_FFFF_FFFF#); x16 := Unsigned_64 (Shift_Right (T_15, 64)); end;
   declare T_17 : constant Unsigned_128 := Unsigned_128 (x16) + Unsigned_128 (x8) + Unsigned_128 (x5);
   begin x17 := Unsigned_64 (T_17 and 16#FFFF_FFFF_FFFF_FFFF#); x18 := Unsigned_64 (Shift_Right (T_17, 64)); end;
   x19 := x18 + x6;

   -- Montgomery reduction 1
   declare T_20 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin x20 := Unsigned_64 (T_20 and 16#FFFF_FFFF_FFFF_FFFF#); x21 := Unsigned_64 (Shift_Right (T_20, 64)); end;
   declare T_22 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#0000_0000_FFFF_FFFF#);
   begin x22 := Unsigned_64 (T_22 and 16#FFFF_FFFF_FFFF_FFFF#); x23 := Unsigned_64 (Shift_Right (T_22, 64)); end;
   declare T_24 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin x24 := Unsigned_64 (T_24 and 16#FFFF_FFFF_FFFF_FFFF#); x25 := Unsigned_64 (Shift_Right (T_24, 64)); end;

   declare T_26 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x25) + Unsigned_128 (x22);
   begin x26 := Unsigned_64 (T_26 and 16#FFFF_FFFF_FFFF_FFFF#); x27 := Unsigned_64 (Shift_Right (T_26, 64)); end;
   x28 := x27 + x23;

   declare T_29 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x11) + Unsigned_128 (x24);
   begin x29 := Unsigned_64 (T_29 and 16#FFFF_FFFF_FFFF_FFFF#); x30 := Unsigned_64 (Shift_Right (T_29, 64)); end;
   declare T_31 : constant Unsigned_128 := Unsigned_128 (x30) + Unsigned_128 (x13) + Unsigned_128 (x26);
   begin x31 := Unsigned_64 (T_31 and 16#FFFF_FFFF_FFFF_FFFF#); x32 := Unsigned_64 (Shift_Right (T_31, 64)); end;
   declare T_33 : constant Unsigned_128 := Unsigned_128 (x32) + Unsigned_128 (x15) + Unsigned_128 (x28);
   begin x33 := Unsigned_64 (T_33 and 16#FFFF_FFFF_FFFF_FFFF#); x34 := Unsigned_64 (Shift_Right (T_33, 64)); end;
   declare T_35 : constant Unsigned_128 := Unsigned_128 (x34) + Unsigned_128 (x17) + Unsigned_128 (x20);
   begin x35 := Unsigned_64 (T_35 and 16#FFFF_FFFF_FFFF_FFFF#); x36 := Unsigned_64 (Shift_Right (T_35, 64)); end;
   declare T_37 : constant Unsigned_128 := Unsigned_128 (x36) + Unsigned_128 (x19) + Unsigned_128 (x21);
   begin x37 := Unsigned_64 (T_37 and 16#FFFF_FFFF_FFFF_FFFF#); x38 := Unsigned_64 (Shift_Right (T_37, 64)); end;

   -- Round 2: multiply by x1 = arg1[1]
   declare T_39 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (Arg1 (3));
   begin x39 := Unsigned_64 (T_39 and 16#FFFF_FFFF_FFFF_FFFF#); x40 := Unsigned_64 (Shift_Right (T_39, 64)); end;
   declare T_41 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (Arg1 (2));
   begin x41 := Unsigned_64 (T_41 and 16#FFFF_FFFF_FFFF_FFFF#); x42 := Unsigned_64 (Shift_Right (T_41, 64)); end;
   declare T_43 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (Arg1 (1));
   begin x43 := Unsigned_64 (T_43 and 16#FFFF_FFFF_FFFF_FFFF#); x44 := Unsigned_64 (Shift_Right (T_43, 64)); end;
   declare T_45 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (Arg1 (0));
   begin x45 := Unsigned_64 (T_45 and 16#FFFF_FFFF_FFFF_FFFF#); x46 := Unsigned_64 (Shift_Right (T_45, 64)); end;

   declare T_47 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x46) + Unsigned_128 (x43);
   begin x47 := Unsigned_64 (T_47 and 16#FFFF_FFFF_FFFF_FFFF#); x48 := Unsigned_64 (Shift_Right (T_47, 64)); end;
   declare T_49 : constant Unsigned_128 := Unsigned_128 (x48) + Unsigned_128 (x44) + Unsigned_128 (x41);
   begin x49 := Unsigned_64 (T_49 and 16#FFFF_FFFF_FFFF_FFFF#); x50 := Unsigned_64 (Shift_Right (T_49, 64)); end;
   declare T_51 : constant Unsigned_128 := Unsigned_128 (x50) + Unsigned_128 (x42) + Unsigned_128 (x39);
   begin x51 := Unsigned_64 (T_51 and 16#FFFF_FFFF_FFFF_FFFF#); x52 := Unsigned_64 (Shift_Right (T_51, 64)); end;
   x53 := x52 + x40;

   declare T_54 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x31) + Unsigned_128 (x45);
   begin x54 := Unsigned_64 (T_54 and 16#FFFF_FFFF_FFFF_FFFF#); x55 := Unsigned_64 (Shift_Right (T_54, 64)); end;
   declare T_56 : constant Unsigned_128 := Unsigned_128 (x55) + Unsigned_128 (x33) + Unsigned_128 (x47);
   begin x56 := Unsigned_64 (T_56 and 16#FFFF_FFFF_FFFF_FFFF#); x57 := Unsigned_64 (Shift_Right (T_56, 64)); end;
   declare T_58 : constant Unsigned_128 := Unsigned_128 (x57) + Unsigned_128 (x35) + Unsigned_128 (x49);
   begin x58 := Unsigned_64 (T_58 and 16#FFFF_FFFF_FFFF_FFFF#); x59 := Unsigned_64 (Shift_Right (T_58, 64)); end;
   declare T_60 : constant Unsigned_128 := Unsigned_128 (x59) + Unsigned_128 (x37) + Unsigned_128 (x51);
   begin x60 := Unsigned_64 (T_60 and 16#FFFF_FFFF_FFFF_FFFF#); x61 := Unsigned_64 (Shift_Right (T_60, 64)); end;
   declare T_62 : constant Unsigned_128 := Unsigned_128 (x61) + Unsigned_128 (x38) + Unsigned_128 (x53);
   begin x62 := Unsigned_64 (T_62 and 16#FFFF_FFFF_FFFF_FFFF#); x63 := Unsigned_64 (Shift_Right (T_62, 64)); end;

   -- Montgomery reduction 2
   declare T_64 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin x64 := Unsigned_64 (T_64 and 16#FFFF_FFFF_FFFF_FFFF#); x65 := Unsigned_64 (Shift_Right (T_64, 64)); end;
   declare T_66 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#0000_0000_FFFF_FFFF#);
   begin x66 := Unsigned_64 (T_66 and 16#FFFF_FFFF_FFFF_FFFF#); x67 := Unsigned_64 (Shift_Right (T_66, 64)); end;
   declare T_68 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin x68 := Unsigned_64 (T_68 and 16#FFFF_FFFF_FFFF_FFFF#); x69 := Unsigned_64 (Shift_Right (T_68, 64)); end;

   declare T_70 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x69) + Unsigned_128 (x66);
   begin x70 := Unsigned_64 (T_70 and 16#FFFF_FFFF_FFFF_FFFF#); x71 := Unsigned_64 (Shift_Right (T_70, 64)); end;
   x72 := x71 + x67;

   declare T_73 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x54) + Unsigned_128 (x68);
   begin x73 := Unsigned_64 (T_73 and 16#FFFF_FFFF_FFFF_FFFF#); x74 := Unsigned_64 (Shift_Right (T_73, 64)); end;
   declare T_75 : constant Unsigned_128 := Unsigned_128 (x74) + Unsigned_128 (x56) + Unsigned_128 (x70);
   begin x75 := Unsigned_64 (T_75 and 16#FFFF_FFFF_FFFF_FFFF#); x76 := Unsigned_64 (Shift_Right (T_75, 64)); end;
   declare T_77 : constant Unsigned_128 := Unsigned_128 (x76) + Unsigned_128 (x58) + Unsigned_128 (x72);
   begin x77 := Unsigned_64 (T_77 and 16#FFFF_FFFF_FFFF_FFFF#); x78 := Unsigned_64 (Shift_Right (T_77, 64)); end;
   declare T_79 : constant Unsigned_128 := Unsigned_128 (x78) + Unsigned_128 (x60) + Unsigned_128 (x64);
   begin x79 := Unsigned_64 (T_79 and 16#FFFF_FFFF_FFFF_FFFF#); x80 := Unsigned_64 (Shift_Right (T_79, 64)); end;
   declare T_81 : constant Unsigned_128 := Unsigned_128 (x80) + Unsigned_128 (x62) + Unsigned_128 (x65);
   begin x81 := Unsigned_64 (T_81 and 16#FFFF_FFFF_FFFF_FFFF#); x82 := Unsigned_64 (Shift_Right (T_81, 64)); end;
   x83 := x82 + x63;

   -- Round 3: multiply by x2 = arg1[2]
   declare T_84 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (Arg1 (3));
   begin x84 := Unsigned_64 (T_84 and 16#FFFF_FFFF_FFFF_FFFF#); x85 := Unsigned_64 (Shift_Right (T_84, 64)); end;
   declare T_86 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (Arg1 (2));
   begin x86 := Unsigned_64 (T_86 and 16#FFFF_FFFF_FFFF_FFFF#); x87 := Unsigned_64 (Shift_Right (T_86, 64)); end;
   declare T_88 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (Arg1 (1));
   begin x88 := Unsigned_64 (T_88 and 16#FFFF_FFFF_FFFF_FFFF#); x89 := Unsigned_64 (Shift_Right (T_88, 64)); end;
   declare T_90 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (Arg1 (0));
   begin x90 := Unsigned_64 (T_90 and 16#FFFF_FFFF_FFFF_FFFF#); x91 := Unsigned_64 (Shift_Right (T_90, 64)); end;

   declare T_92 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x91) + Unsigned_128 (x88);
   begin x92 := Unsigned_64 (T_92 and 16#FFFF_FFFF_FFFF_FFFF#); x93 := Unsigned_64 (Shift_Right (T_92, 64)); end;
   declare T_94 : constant Unsigned_128 := Unsigned_128 (x93) + Unsigned_128 (x89) + Unsigned_128 (x86);
   begin x94 := Unsigned_64 (T_94 and 16#FFFF_FFFF_FFFF_FFFF#); x95 := Unsigned_64 (Shift_Right (T_94, 64)); end;
   declare T_96 : constant Unsigned_128 := Unsigned_128 (x95) + Unsigned_128 (x87) + Unsigned_128 (x84);
   begin x96 := Unsigned_64 (T_96 and 16#FFFF_FFFF_FFFF_FFFF#); x97 := Unsigned_64 (Shift_Right (T_96, 64)); end;
   x98 := x97 + x85;

   declare T_99 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x75) + Unsigned_128 (x90);
   begin x99 := Unsigned_64 (T_99 and 16#FFFF_FFFF_FFFF_FFFF#); x100 := Unsigned_64 (Shift_Right (T_99, 64)); end;
   declare T_101 : constant Unsigned_128 := Unsigned_128 (x100) + Unsigned_128 (x77) + Unsigned_128 (x92);
   begin x101 := Unsigned_64 (T_101 and 16#FFFF_FFFF_FFFF_FFFF#); x102 := Unsigned_64 (Shift_Right (T_101, 64)); end;
   declare T_103 : constant Unsigned_128 := Unsigned_128 (x102) + Unsigned_128 (x79) + Unsigned_128 (x94);
   begin x103 := Unsigned_64 (T_103 and 16#FFFF_FFFF_FFFF_FFFF#); x104 := Unsigned_64 (Shift_Right (T_103, 64)); end;
   declare T_105 : constant Unsigned_128 := Unsigned_128 (x104) + Unsigned_128 (x81) + Unsigned_128 (x96);
   begin x105 := Unsigned_64 (T_105 and 16#FFFF_FFFF_FFFF_FFFF#); x106 := Unsigned_64 (Shift_Right (T_105, 64)); end;
   declare T_107 : constant Unsigned_128 := Unsigned_128 (x106) + Unsigned_128 (x83) + Unsigned_128 (x98);
   begin x107 := Unsigned_64 (T_107 and 16#FFFF_FFFF_FFFF_FFFF#); x108 := Unsigned_64 (Shift_Right (T_107, 64)); end;

   -- Montgomery reduction 3
   declare T_109 : constant Unsigned_128 := Unsigned_128 (x99) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin x109 := Unsigned_64 (T_109 and 16#FFFF_FFFF_FFFF_FFFF#); x110 := Unsigned_64 (Shift_Right (T_109, 64)); end;
   declare T_111 : constant Unsigned_128 := Unsigned_128 (x99) * Unsigned_128 (16#0000_0000_FFFF_FFFF#);
   begin x111 := Unsigned_64 (T_111 and 16#FFFF_FFFF_FFFF_FFFF#); x112 := Unsigned_64 (Shift_Right (T_111, 64)); end;
   declare T_113 : constant Unsigned_128 := Unsigned_128 (x99) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin x113 := Unsigned_64 (T_113 and 16#FFFF_FFFF_FFFF_FFFF#); x114 := Unsigned_64 (Shift_Right (T_113, 64)); end;

   declare T_115 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x114) + Unsigned_128 (x111);
   begin x115 := Unsigned_64 (T_115 and 16#FFFF_FFFF_FFFF_FFFF#); x116 := Unsigned_64 (Shift_Right (T_115, 64)); end;
   x117 := x116 + x112;

   declare T_118 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x99) + Unsigned_128 (x113);
   begin x118 := Unsigned_64 (T_118 and 16#FFFF_FFFF_FFFF_FFFF#); x119 := Unsigned_64 (Shift_Right (T_118, 64)); end;
   declare T_120 : constant Unsigned_128 := Unsigned_128 (x119) + Unsigned_128 (x101) + Unsigned_128 (x115);
   begin x120 := Unsigned_64 (T_120 and 16#FFFF_FFFF_FFFF_FFFF#); x121 := Unsigned_64 (Shift_Right (T_120, 64)); end;
   declare T_122 : constant Unsigned_128 := Unsigned_128 (x121) + Unsigned_128 (x103) + Unsigned_128 (x117);
   begin x122 := Unsigned_64 (T_122 and 16#FFFF_FFFF_FFFF_FFFF#); x123 := Unsigned_64 (Shift_Right (T_122, 64)); end;
   declare T_124 : constant Unsigned_128 := Unsigned_128 (x123) + Unsigned_128 (x105) + Unsigned_128 (x109);
   begin x124 := Unsigned_64 (T_124 and 16#FFFF_FFFF_FFFF_FFFF#); x125 := Unsigned_64 (Shift_Right (T_124, 64)); end;
   declare T_126 : constant Unsigned_128 := Unsigned_128 (x125) + Unsigned_128 (x107) + Unsigned_128 (x110);
   begin x126 := Unsigned_64 (T_126 and 16#FFFF_FFFF_FFFF_FFFF#); x127 := Unsigned_64 (Shift_Right (T_126, 64)); end;
   x128 := x127 + x108;

   -- Round 4: multiply by x3 = arg1[3]
   declare T_129 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (Arg1 (3));
   begin x129 := Unsigned_64 (T_129 and 16#FFFF_FFFF_FFFF_FFFF#); x130 := Unsigned_64 (Shift_Right (T_129, 64)); end;
   declare T_131 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (Arg1 (2));
   begin x131 := Unsigned_64 (T_131 and 16#FFFF_FFFF_FFFF_FFFF#); x132 := Unsigned_64 (Shift_Right (T_131, 64)); end;
   declare T_133 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (Arg1 (1));
   begin x133 := Unsigned_64 (T_133 and 16#FFFF_FFFF_FFFF_FFFF#); x134 := Unsigned_64 (Shift_Right (T_133, 64)); end;
   declare T_135 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (Arg1 (0));
   begin x135 := Unsigned_64 (T_135 and 16#FFFF_FFFF_FFFF_FFFF#); x136 := Unsigned_64 (Shift_Right (T_135, 64)); end;

   declare T_137 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x136) + Unsigned_128 (x133);
   begin x137 := Unsigned_64 (T_137 and 16#FFFF_FFFF_FFFF_FFFF#); x138 := Unsigned_64 (Shift_Right (T_137, 64)); end;
   declare T_139 : constant Unsigned_128 := Unsigned_128 (x138) + Unsigned_128 (x134) + Unsigned_128 (x131);
   begin x139 := Unsigned_64 (T_139 and 16#FFFF_FFFF_FFFF_FFFF#); x140 := Unsigned_64 (Shift_Right (T_139, 64)); end;
   declare T_141 : constant Unsigned_128 := Unsigned_128 (x140) + Unsigned_128 (x132) + Unsigned_128 (x129);
   begin x141 := Unsigned_64 (T_141 and 16#FFFF_FFFF_FFFF_FFFF#); x142 := Unsigned_64 (Shift_Right (T_141, 64)); end;
   x143 := x142 + x130;

   declare T_144 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x120) + Unsigned_128 (x135);
   begin x144 := Unsigned_64 (T_144 and 16#FFFF_FFFF_FFFF_FFFF#); x145 := Unsigned_64 (Shift_Right (T_144, 64)); end;
   declare T_146 : constant Unsigned_128 := Unsigned_128 (x145) + Unsigned_128 (x122) + Unsigned_128 (x137);
   begin x146 := Unsigned_64 (T_146 and 16#FFFF_FFFF_FFFF_FFFF#); x147 := Unsigned_64 (Shift_Right (T_146, 64)); end;
   declare T_148 : constant Unsigned_128 := Unsigned_128 (x147) + Unsigned_128 (x124) + Unsigned_128 (x139);
   begin x148 := Unsigned_64 (T_148 and 16#FFFF_FFFF_FFFF_FFFF#); x149 := Unsigned_64 (Shift_Right (T_148, 64)); end;
   declare T_150 : constant Unsigned_128 := Unsigned_128 (x149) + Unsigned_128 (x126) + Unsigned_128 (x141);
   begin x150 := Unsigned_64 (T_150 and 16#FFFF_FFFF_FFFF_FFFF#); x151 := Unsigned_64 (Shift_Right (T_150, 64)); end;
   declare T_152 : constant Unsigned_128 := Unsigned_128 (x151) + Unsigned_128 (x128) + Unsigned_128 (x143);
   begin x152 := Unsigned_64 (T_152 and 16#FFFF_FFFF_FFFF_FFFF#); x153 := Unsigned_64 (Shift_Right (T_152, 64)); end;

   -- Montgomery reduction 4
   declare T_154 : constant Unsigned_128 := Unsigned_128 (x144) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin x154 := Unsigned_64 (T_154 and 16#FFFF_FFFF_FFFF_FFFF#); x155 := Unsigned_64 (Shift_Right (T_154, 64)); end;
   declare T_156 : constant Unsigned_128 := Unsigned_128 (x144) * Unsigned_128 (16#0000_0000_FFFF_FFFF#);
   begin x156 := Unsigned_64 (T_156 and 16#FFFF_FFFF_FFFF_FFFF#); x157 := Unsigned_64 (Shift_Right (T_156, 64)); end;
   declare T_158 : constant Unsigned_128 := Unsigned_128 (x144) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin x158 := Unsigned_64 (T_158 and 16#FFFF_FFFF_FFFF_FFFF#); x159 := Unsigned_64 (Shift_Right (T_158, 64)); end;

   declare T_160 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x159) + Unsigned_128 (x156);
   begin x160 := Unsigned_64 (T_160 and 16#FFFF_FFFF_FFFF_FFFF#); x161 := Unsigned_64 (Shift_Right (T_160, 64)); end;
   x162 := x161 + x157;

   declare T_163 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x144) + Unsigned_128 (x158);
   begin x163 := Unsigned_64 (T_163 and 16#FFFF_FFFF_FFFF_FFFF#); x164 := Unsigned_64 (Shift_Right (T_163, 64)); end;
   declare T_165 : constant Unsigned_128 := Unsigned_128 (x164) + Unsigned_128 (x146) + Unsigned_128 (x160);
   begin x165 := Unsigned_64 (T_165 and 16#FFFF_FFFF_FFFF_FFFF#); x166 := Unsigned_64 (Shift_Right (T_165, 64)); end;
   declare T_167 : constant Unsigned_128 := Unsigned_128 (x166) + Unsigned_128 (x148) + Unsigned_128 (x162);
   begin x167 := Unsigned_64 (T_167 and 16#FFFF_FFFF_FFFF_FFFF#); x168 := Unsigned_64 (Shift_Right (T_167, 64)); end;
   declare T_169 : constant Unsigned_128 := Unsigned_128 (x168) + Unsigned_128 (x150) + Unsigned_128 (x154);
   begin x169 := Unsigned_64 (T_169 and 16#FFFF_FFFF_FFFF_FFFF#); x170 := Unsigned_64 (Shift_Right (T_169, 64)); end;
   declare T_171 : constant Unsigned_128 := Unsigned_128 (x170) + Unsigned_128 (x152) + Unsigned_128 (x155);
   begin x171 := Unsigned_64 (T_171 and 16#FFFF_FFFF_FFFF_FFFF#); x172 := Unsigned_64 (Shift_Right (T_171, 64)); end;
   x173 := x172 + x153;

   -- Final conditional subtraction of p
   declare T_174 : constant Unsigned_128 := Unsigned_128 (x165) - Unsigned_128 (0) - Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin x174 := Unsigned_64 (T_174 and 16#FFFF_FFFF_FFFF_FFFF#); x175 := Unsigned_64 (Shift_Right (T_174, 64)) and 1; end;
   declare T_176 : constant Unsigned_128 := Unsigned_128 (x167) - Unsigned_128 (x175) - Unsigned_128 (16#0000_0000_FFFF_FFFF#);
   begin x176 := Unsigned_64 (T_176 and 16#FFFF_FFFF_FFFF_FFFF#); x177 := Unsigned_64 (Shift_Right (T_176, 64)) and 1; end;
   declare T_178 : constant Unsigned_128 := Unsigned_128 (x169) - Unsigned_128 (x177) - Unsigned_128 (0);
   begin x178 := Unsigned_64 (T_178 and 16#FFFF_FFFF_FFFF_FFFF#); x179 := Unsigned_64 (Shift_Right (T_178, 64)) and 1; end;
   declare T_180 : constant Unsigned_128 := Unsigned_128 (x171) - Unsigned_128 (x179) - Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin x180 := Unsigned_64 (T_180 and 16#FFFF_FFFF_FFFF_FFFF#); x181 := Unsigned_64 (Shift_Right (T_180, 64)) and 1; end;
   declare T_182 : constant Unsigned_128 := Unsigned_128 (x173) - Unsigned_128 (x181) - Unsigned_128 (0);
   begin x182 := Unsigned_64 (T_182 and 16#FFFF_FFFF_FFFF_FFFF#); x183 := Unsigned_64 (Shift_Right (T_182, 64)) and 1; end;

   -- Conditional move
   declare Mask_184 : constant Unsigned_64 := -(x183 and 1);
   begin x184 := (Mask_184 and x165) or ((not Mask_184) and x174); end;
   declare Mask_185 : constant Unsigned_64 := -(x183 and 1);
   begin x185 := (Mask_185 and x167) or ((not Mask_185) and x176); end;
   declare Mask_186 : constant Unsigned_64 := -(x183 and 1);
   begin x186 := (Mask_186 and x169) or ((not Mask_186) and x178); end;
   declare Mask_187 : constant Unsigned_64 := -(x183 and 1);
   begin x187 := (Mask_187 and x171) or ((not Mask_187) and x180); end;

   Out1 := (x184, x185, x186, x187);
   return Out1;
end Sqr;

   --  add: out1 := arg1 + arg2 mod p
   function Add (Arg1, Arg2 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8   : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
      x17, x18, x19, x20, x21, x22      : Unsigned_64;
   begin
      --  4-limb addition with carry
      declare
         T_1 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (Arg1 (0)) + Unsigned_128 (Arg2 (0));
      begin
         x1 := Unsigned_64 (T_1 and 16#FFFF_FFFF_FFFF_FFFF#);
         x2 := Unsigned_64 (Shift_Right (T_1, 64));
      end;
      declare
         T_3 : constant Unsigned_128 := Unsigned_128 (x2) + Unsigned_128 (Arg1 (1)) + Unsigned_128 (Arg2 (1));
      begin
         x3 := Unsigned_64 (T_3 and 16#FFFF_FFFF_FFFF_FFFF#);
         x4 := Unsigned_64 (Shift_Right (T_3, 64));
      end;
      declare
         T_5 : constant Unsigned_128 := Unsigned_128 (x4) + Unsigned_128 (Arg1 (2)) + Unsigned_128 (Arg2 (2));
      begin
         x5 := Unsigned_64 (T_5 and 16#FFFF_FFFF_FFFF_FFFF#);
         x6 := Unsigned_64 (Shift_Right (T_5, 64));
      end;
      declare
         T_7 : constant Unsigned_128 := Unsigned_128 (x6) + Unsigned_128 (Arg1 (3)) + Unsigned_128 (Arg2 (3));
      begin
         x7 := Unsigned_64 (T_7 and 16#FFFF_FFFF_FFFF_FFFF#);
         x8 := Unsigned_64 (Shift_Right (T_7, 64));
      end;
      --  Tentatively subtract p
      declare
         T_9 : constant Unsigned_128 := Unsigned_128 (x1) - Unsigned_128 (0) - Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
      begin
         x9  := Unsigned_64 (T_9 and 16#FFFF_FFFF_FFFF_FFFF#);
         x10 := Unsigned_64 (Shift_Right (T_9, 64)) and 1;
      end;
      declare
         T_11 : constant Unsigned_128 := Unsigned_128 (x3) - Unsigned_128 (x10) - Unsigned_128 (16#0000_0000_FFFF_FFFF#);
      begin
         x11 := Unsigned_64 (T_11 and 16#FFFF_FFFF_FFFF_FFFF#);
         x12 := Unsigned_64 (Shift_Right (T_11, 64)) and 1;
      end;
      declare
         T_13 : constant Unsigned_128 := Unsigned_128 (x5) - Unsigned_128 (x12) - Unsigned_128 (0);
      begin
         x13 := Unsigned_64 (T_13 and 16#FFFF_FFFF_FFFF_FFFF#);
         x14 := Unsigned_64 (Shift_Right (T_13, 64)) and 1;
      end;
      declare
         T_15 : constant Unsigned_128 := Unsigned_128 (x7) - Unsigned_128 (x14) - Unsigned_128 (16#FFFF_FFFF_0000_0001#);
      begin
         x15 := Unsigned_64 (T_15 and 16#FFFF_FFFF_FFFF_FFFF#);
         x16 := Unsigned_64 (Shift_Right (T_15, 64)) and 1;
      end;
      declare
         T_17 : constant Unsigned_128 := Unsigned_128 (x8) - Unsigned_128 (x16) - Unsigned_128 (0);
      begin
         x17 := Unsigned_64 (T_17 and 16#FFFF_FFFF_FFFF_FFFF#);
         x18 := Unsigned_64 (Shift_Right (T_17, 64)) and 1;
      end;
      --  Conditional select: if borrow, keep sum; else keep subtracted
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x19 := (Mask and x1) or ((not Mask) and x9);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x20 := (Mask and x3) or ((not Mask) and x11);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x21 := (Mask and x5) or ((not Mask) and x13);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x22 := (Mask and x7) or ((not Mask) and x15);
      end;
      Out1 := (x19, x20, x21, x22);
      return Out1;
   end Add;

   --  sub: out1 := arg1 - arg2 mod p
   function Sub (Arg1, Arg2 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16, x17 : Unsigned_64;
   begin
      --  4-limb subtraction with borrow
      declare
         T_1 : constant Unsigned_128 := Unsigned_128 (Arg1 (0)) - Unsigned_128 (0) - Unsigned_128 (Arg2 (0));
      begin
         x1 := Unsigned_64 (T_1 and 16#FFFF_FFFF_FFFF_FFFF#);
         x2 := Unsigned_64 (Shift_Right (T_1, 64)) and 1;
      end;
      declare
         T_3 : constant Unsigned_128 := Unsigned_128 (Arg1 (1)) - Unsigned_128 (x2) - Unsigned_128 (Arg2 (1));
      begin
         x3 := Unsigned_64 (T_3 and 16#FFFF_FFFF_FFFF_FFFF#);
         x4 := Unsigned_64 (Shift_Right (T_3, 64)) and 1;
      end;
      declare
         T_5 : constant Unsigned_128 := Unsigned_128 (Arg1 (2)) - Unsigned_128 (x4) - Unsigned_128 (Arg2 (2));
      begin
         x5 := Unsigned_64 (T_5 and 16#FFFF_FFFF_FFFF_FFFF#);
         x6 := Unsigned_64 (Shift_Right (T_5, 64)) and 1;
      end;
      declare
         T_7 : constant Unsigned_128 := Unsigned_128 (Arg1 (3)) - Unsigned_128 (x6) - Unsigned_128 (Arg2 (3));
      begin
         x7 := Unsigned_64 (T_7 and 16#FFFF_FFFF_FFFF_FFFF#);
         x8 := Unsigned_64 (Shift_Right (T_7, 64)) and 1;
      end;
      --  If borrow, add p back (conditional on x8)
      declare Mask : constant Unsigned_64 := -(x8 and 1); begin
         x9 := Mask and 16#FFFF_FFFF_FFFF_FFFF#;  --  = 0 or p[0]
      end;
      declare
         T_10 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x1) + Unsigned_128 (x9);
      begin
         x10 := Unsigned_64 (T_10 and 16#FFFF_FFFF_FFFF_FFFF#);
         x11 := Unsigned_64 (Shift_Right (T_10, 64));
      end;
      declare
         T_12 : constant Unsigned_128 := Unsigned_128 (x11) + Unsigned_128 (x3) + Unsigned_128 (x9 and 16#0000_0000_FFFF_FFFF#);
      begin
         x12 := Unsigned_64 (T_12 and 16#FFFF_FFFF_FFFF_FFFF#);
         x13 := Unsigned_64 (Shift_Right (T_12, 64));
      end;
      declare
         T_14 : constant Unsigned_128 := Unsigned_128 (x13) + Unsigned_128 (x5) + Unsigned_128 (0);
      begin
         x14 := Unsigned_64 (T_14 and 16#FFFF_FFFF_FFFF_FFFF#);
         x15 := Unsigned_64 (Shift_Right (T_14, 64));
      end;
      declare
         T_16 : constant Unsigned_128 := Unsigned_128 (x15) + Unsigned_128 (x7) + Unsigned_128 (x9 and 16#FFFF_FFFF_0000_0001#);
      begin
         x16 := Unsigned_64 (T_16 and 16#FFFF_FFFF_FFFF_FFFF#);
         x17 := Unsigned_64 (Shift_Right (T_16, 64));
      end;
      Out1 := (x10, x12, x14, x16);
      return Out1;
   end Sub;

   --  opp: out1 := -arg1 mod p
   function Opp (Arg1 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16, x17 : Unsigned_64;
   begin
      --  Subtract arg1 from 0 with borrow chain
      declare
         T_1 : constant Unsigned_128 := Unsigned_128 (0) - Unsigned_128 (0) - Unsigned_128 (Arg1 (0));
      begin
         x1 := Unsigned_64 (T_1 and 16#FFFF_FFFF_FFFF_FFFF#);
         x2 := Unsigned_64 (Shift_Right (T_1, 64)) and 1;
      end;
      declare
         T_3 : constant Unsigned_128 := Unsigned_128 (0) - Unsigned_128 (x2) - Unsigned_128 (Arg1 (1));
      begin
         x3 := Unsigned_64 (T_3 and 16#FFFF_FFFF_FFFF_FFFF#);
         x4 := Unsigned_64 (Shift_Right (T_3, 64)) and 1;
      end;
      declare
         T_5 : constant Unsigned_128 := Unsigned_128 (0) - Unsigned_128 (x4) - Unsigned_128 (Arg1 (2));
      begin
         x5 := Unsigned_64 (T_5 and 16#FFFF_FFFF_FFFF_FFFF#);
         x6 := Unsigned_64 (Shift_Right (T_5, 64)) and 1;
      end;
      declare
         T_7 : constant Unsigned_128 := Unsigned_128 (0) - Unsigned_128 (x6) - Unsigned_128 (Arg1 (3));
      begin
         x7 := Unsigned_64 (T_7 and 16#FFFF_FFFF_FFFF_FFFF#);
         x8 := Unsigned_64 (Shift_Right (T_7, 64)) and 1;
      end;
      --  Conditionally add p
      declare Mask : constant Unsigned_64 := -(x8 and 1); begin
         x9 := Mask and 16#FFFF_FFFF_FFFF_FFFF#;
      end;
      declare
         T_10 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x1) + Unsigned_128 (x9);
      begin
         x10 := Unsigned_64 (T_10 and 16#FFFF_FFFF_FFFF_FFFF#);
         x11 := Unsigned_64 (Shift_Right (T_10, 64));
      end;
      declare
         T_12 : constant Unsigned_128 := Unsigned_128 (x11) + Unsigned_128 (x3) + Unsigned_128 (x9 and 16#0000_0000_FFFF_FFFF#);
      begin
         x12 := Unsigned_64 (T_12 and 16#FFFF_FFFF_FFFF_FFFF#);
         x13 := Unsigned_64 (Shift_Right (T_12, 64));
      end;
      declare
         T_14 : constant Unsigned_128 := Unsigned_128 (x13) + Unsigned_128 (x5) + Unsigned_128 (0);
      begin
         x14 := Unsigned_64 (T_14 and 16#FFFF_FFFF_FFFF_FFFF#);
         x15 := Unsigned_64 (Shift_Right (T_14, 64));
      end;
      declare
         T_16 : constant Unsigned_128 := Unsigned_128 (x15) + Unsigned_128 (x7) + Unsigned_128 (x9 and 16#FFFF_FFFF_0000_0001#);
      begin
         x16 := Unsigned_64 (T_16 and 16#FFFF_FFFF_FFFF_FFFF#);
         x17 := Unsigned_64 (Shift_Right (T_16, 64));
      end;
      Out1 := (x10, x12, x14, x16);
      return Out1;
   end Opp;

   --  selectznz: constant-time conditional select
   function Selectznz (Cond : Unsigned_64;
                        Arg2, Arg3 : FE) return FE is
      Out1 : FE;
      Mask : constant Unsigned_64 := -(Cond and 1);
   begin
      --  if Cond = 0, select Arg2; else select Arg3
      Out1 := ((Mask and Arg3 (0)) or ((not Mask) and Arg2 (0)),
               (Mask and Arg3 (1)) or ((not Mask) and Arg2 (1)),
               (Mask and Arg3 (2)) or ((not Mask) and Arg2 (2)),
               (Mask and Arg3 (3)) or ((not Mask) and Arg2 (3)));
      return Out1;
   end Selectznz;

   --  nonzero
   procedure Nonzero (Out1 : out Unsigned_64; Arg1 : FE) is
   begin
      Out1 := Arg1 (0) or Arg1 (1) or Arg1 (2) or Arg1 (3);
   end Nonzero;

   --  to_bytes: field element to 32 little-endian bytes
   procedure To_Bytes (Out1 : out Byte_Seq; Arg1 : FE) is
      F : constant I32 := Out1'First;
   begin
      Out1 := (others => 0);
      for Limb_Idx in 0 .. 3 loop
         declare
            V : Unsigned_64 := Arg1 (Limb_Idx);
            Base : constant I32 := F + I32 (Limb_Idx) * 8;
         begin
            for B in 0 .. 7 loop
               Out1 (Base + I32 (B)) := Byte (V and 16#FF#);
               V := Shift_Right (V, 8);
            end loop;
         end;
      end loop;
   end To_Bytes;

   --  from_bytes: 32 little-endian bytes to field element
   function From_Bytes (Arg1 : Byte_Seq) return FE is
      Out1 : FE;
      F : constant I32 := Arg1'First;
   begin
      for Limb_Idx in 0 .. 3 loop
         declare
            V : Unsigned_64 := 0;
            Base : constant I32 := F + I32 (Limb_Idx) * 8;
         begin
            for B in reverse 0 .. 7 loop
               V := Shift_Left (V, 8) or Unsigned_64 (Arg1 (Base + I32 (B)));
            end loop;
            Out1 (Limb_Idx) := V;
         end;
      end loop;
      return Out1;
   end From_Bytes;

   --  from_montgomery / to_montgomery
   --  Translated from fiat_p256_64.c lines 921-1340

   function From_Montgomery (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24 : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32 : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40 : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48 : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56 : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64 : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72 : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80 : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88 : Unsigned_64;
   x89, x90 : Unsigned_64;
begin
   --  Round 1: arg1[0]
   x1 := Arg1 (0);

   --  mulx_u64(&x2, &x3, x1, 0xffffffff00000001)
   declare
      T_2 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x2 := Unsigned_64 (T_2 and 16#FFFF_FFFF_FFFF_FFFF#);
      x3 := Unsigned_64 (Shift_Right (T_2, 64));
   end;

   --  mulx_u64(&x4, &x5, x1, 0xffffffff)
   declare
      T_4 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x4 := Unsigned_64 (T_4 and 16#FFFF_FFFF_FFFF_FFFF#);
      x5 := Unsigned_64 (Shift_Right (T_4, 64));
   end;

   --  mulx_u64(&x6, &x7, x1, 0xffffffffffffffff)
   declare
      T_6 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x6 := Unsigned_64 (T_6 and 16#FFFF_FFFF_FFFF_FFFF#);
      x7 := Unsigned_64 (Shift_Right (T_6, 64));
   end;

   --  addcarryx_u64(&x8, &x9, 0x0, x7, x4)
   declare
      T_8 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x7) + Unsigned_128 (x4);
   begin
      x8 := Unsigned_64 (T_8 and 16#FFFF_FFFF_FFFF_FFFF#);
      x9 := Unsigned_64 (Shift_Right (T_8, 64));
   end;

   --  addcarryx_u64(&x10, &x11, 0x0, x1, x6)
   declare
      T_10 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x1) + Unsigned_128 (x6);
   begin
      x10 := Unsigned_64 (T_10 and 16#FFFF_FFFF_FFFF_FFFF#);
      x11 := Unsigned_64 (Shift_Right (T_10, 64));
   end;

   --  addcarryx_u64(&x12, &x13, x11, 0x0, x8)
   declare
      T_12 : constant Unsigned_128 := Unsigned_128 (x11) + Unsigned_128 (0) + Unsigned_128 (x8);
   begin
      x12 := Unsigned_64 (T_12 and 16#FFFF_FFFF_FFFF_FFFF#);
      x13 := Unsigned_64 (Shift_Right (T_12, 64));
   end;

   --  addcarryx_u64(&x14, &x15, 0x0, x12, arg1[1])
   declare
      T_14 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x12) + Unsigned_128 (Arg1 (1));
   begin
      x14 := Unsigned_64 (T_14 and 16#FFFF_FFFF_FFFF_FFFF#);
      x15 := Unsigned_64 (Shift_Right (T_14, 64));
   end;

   --  Round 2: x14
   --  mulx_u64(&x16, &x17, x14, 0xffffffff00000001)
   declare
      T_16 : constant Unsigned_128 := Unsigned_128 (x14) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x16 := Unsigned_64 (T_16 and 16#FFFF_FFFF_FFFF_FFFF#);
      x17 := Unsigned_64 (Shift_Right (T_16, 64));
   end;

   --  mulx_u64(&x18, &x19, x14, 0xffffffff)
   declare
      T_18 : constant Unsigned_128 := Unsigned_128 (x14) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x18 := Unsigned_64 (T_18 and 16#FFFF_FFFF_FFFF_FFFF#);
      x19 := Unsigned_64 (Shift_Right (T_18, 64));
   end;

   --  mulx_u64(&x20, &x21, x14, 0xffffffffffffffff)
   declare
      T_20 : constant Unsigned_128 := Unsigned_128 (x14) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x20 := Unsigned_64 (T_20 and 16#FFFF_FFFF_FFFF_FFFF#);
      x21 := Unsigned_64 (Shift_Right (T_20, 64));
   end;

   --  addcarryx_u64(&x22, &x23, 0x0, x21, x18)
   declare
      T_22 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x21) + Unsigned_128 (x18);
   begin
      x22 := Unsigned_64 (T_22 and 16#FFFF_FFFF_FFFF_FFFF#);
      x23 := Unsigned_64 (Shift_Right (T_22, 64));
   end;

   --  addcarryx_u64(&x24, &x25, 0x0, x14, x20)
   declare
      T_24 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x14) + Unsigned_128 (x20);
   begin
      x24 := Unsigned_64 (T_24 and 16#FFFF_FFFF_FFFF_FFFF#);
      x25 := Unsigned_64 (Shift_Right (T_24, 64));
   end;

   --  addcarryx_u64(&x26, &x27, x25, (x15 + (x13 + (x9 + x5))), x22)
   declare
      T_26 : constant Unsigned_128 := Unsigned_128 (x25) + Unsigned_128 (x15 + (x13 + (x9 + x5))) + Unsigned_128 (x22);
   begin
      x26 := Unsigned_64 (T_26 and 16#FFFF_FFFF_FFFF_FFFF#);
      x27 := Unsigned_64 (Shift_Right (T_26, 64));
   end;

   --  addcarryx_u64(&x28, &x29, x27, x2, (x23 + x19))
   declare
      T_28 : constant Unsigned_128 := Unsigned_128 (x27) + Unsigned_128 (x2) + Unsigned_128 (x23 + x19);
   begin
      x28 := Unsigned_64 (T_28 and 16#FFFF_FFFF_FFFF_FFFF#);
      x29 := Unsigned_64 (Shift_Right (T_28, 64));
   end;

   --  addcarryx_u64(&x30, &x31, x29, x3, x16)
   declare
      T_30 : constant Unsigned_128 := Unsigned_128 (x29) + Unsigned_128 (x3) + Unsigned_128 (x16);
   begin
      x30 := Unsigned_64 (T_30 and 16#FFFF_FFFF_FFFF_FFFF#);
      x31 := Unsigned_64 (Shift_Right (T_30, 64));
   end;

   --  addcarryx_u64(&x32, &x33, 0x0, x26, arg1[2])
   declare
      T_32 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x26) + Unsigned_128 (Arg1 (2));
   begin
      x32 := Unsigned_64 (T_32 and 16#FFFF_FFFF_FFFF_FFFF#);
      x33 := Unsigned_64 (Shift_Right (T_32, 64));
   end;

   --  addcarryx_u64(&x34, &x35, x33, x28, 0x0)
   declare
      T_34 : constant Unsigned_128 := Unsigned_128 (x33) + Unsigned_128 (x28) + Unsigned_128 (0);
   begin
      x34 := Unsigned_64 (T_34 and 16#FFFF_FFFF_FFFF_FFFF#);
      x35 := Unsigned_64 (Shift_Right (T_34, 64));
   end;

   --  addcarryx_u64(&x36, &x37, x35, x30, 0x0)
   declare
      T_36 : constant Unsigned_128 := Unsigned_128 (x35) + Unsigned_128 (x30) + Unsigned_128 (0);
   begin
      x36 := Unsigned_64 (T_36 and 16#FFFF_FFFF_FFFF_FFFF#);
      x37 := Unsigned_64 (Shift_Right (T_36, 64));
   end;

   --  Round 3: x32
   --  mulx_u64(&x38, &x39, x32, 0xffffffff00000001)
   declare
      T_38 : constant Unsigned_128 := Unsigned_128 (x32) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x38 := Unsigned_64 (T_38 and 16#FFFF_FFFF_FFFF_FFFF#);
      x39 := Unsigned_64 (Shift_Right (T_38, 64));
   end;

   --  mulx_u64(&x40, &x41, x32, 0xffffffff)
   declare
      T_40 : constant Unsigned_128 := Unsigned_128 (x32) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x40 := Unsigned_64 (T_40 and 16#FFFF_FFFF_FFFF_FFFF#);
      x41 := Unsigned_64 (Shift_Right (T_40, 64));
   end;

   --  mulx_u64(&x42, &x43, x32, 0xffffffffffffffff)
   declare
      T_42 : constant Unsigned_128 := Unsigned_128 (x32) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x42 := Unsigned_64 (T_42 and 16#FFFF_FFFF_FFFF_FFFF#);
      x43 := Unsigned_64 (Shift_Right (T_42, 64));
   end;

   --  addcarryx_u64(&x44, &x45, 0x0, x43, x40)
   declare
      T_44 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x43) + Unsigned_128 (x40);
   begin
      x44 := Unsigned_64 (T_44 and 16#FFFF_FFFF_FFFF_FFFF#);
      x45 := Unsigned_64 (Shift_Right (T_44, 64));
   end;

   --  addcarryx_u64(&x46, &x47, 0x0, x32, x42)
   declare
      T_46 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x32) + Unsigned_128 (x42);
   begin
      x46 := Unsigned_64 (T_46 and 16#FFFF_FFFF_FFFF_FFFF#);
      x47 := Unsigned_64 (Shift_Right (T_46, 64));
   end;

   --  addcarryx_u64(&x48, &x49, x47, x34, x44)
   declare
      T_48 : constant Unsigned_128 := Unsigned_128 (x47) + Unsigned_128 (x34) + Unsigned_128 (x44);
   begin
      x48 := Unsigned_64 (T_48 and 16#FFFF_FFFF_FFFF_FFFF#);
      x49 := Unsigned_64 (Shift_Right (T_48, 64));
   end;

   --  addcarryx_u64(&x50, &x51, x49, x36, (x45 + x41))
   declare
      T_50 : constant Unsigned_128 := Unsigned_128 (x49) + Unsigned_128 (x36) + Unsigned_128 (x45 + x41);
   begin
      x50 := Unsigned_64 (T_50 and 16#FFFF_FFFF_FFFF_FFFF#);
      x51 := Unsigned_64 (Shift_Right (T_50, 64));
   end;

   --  addcarryx_u64(&x52, &x53, x51, (x37 + (x31 + x17)), x38)
   declare
      T_52 : constant Unsigned_128 := Unsigned_128 (x51) + Unsigned_128 (x37 + (x31 + x17)) + Unsigned_128 (x38);
   begin
      x52 := Unsigned_64 (T_52 and 16#FFFF_FFFF_FFFF_FFFF#);
      x53 := Unsigned_64 (Shift_Right (T_52, 64));
   end;

   --  addcarryx_u64(&x54, &x55, 0x0, x48, arg1[3])
   declare
      T_54 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x48) + Unsigned_128 (Arg1 (3));
   begin
      x54 := Unsigned_64 (T_54 and 16#FFFF_FFFF_FFFF_FFFF#);
      x55 := Unsigned_64 (Shift_Right (T_54, 64));
   end;

   --  addcarryx_u64(&x56, &x57, x55, x50, 0x0)
   declare
      T_56 : constant Unsigned_128 := Unsigned_128 (x55) + Unsigned_128 (x50) + Unsigned_128 (0);
   begin
      x56 := Unsigned_64 (T_56 and 16#FFFF_FFFF_FFFF_FFFF#);
      x57 := Unsigned_64 (Shift_Right (T_56, 64));
   end;

   --  addcarryx_u64(&x58, &x59, x57, x52, 0x0)
   declare
      T_58 : constant Unsigned_128 := Unsigned_128 (x57) + Unsigned_128 (x52) + Unsigned_128 (0);
   begin
      x58 := Unsigned_64 (T_58 and 16#FFFF_FFFF_FFFF_FFFF#);
      x59 := Unsigned_64 (Shift_Right (T_58, 64));
   end;

   --  Round 4: x54
   --  mulx_u64(&x60, &x61, x54, 0xffffffff00000001)
   declare
      T_60 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x60 := Unsigned_64 (T_60 and 16#FFFF_FFFF_FFFF_FFFF#);
      x61 := Unsigned_64 (Shift_Right (T_60, 64));
   end;

   --  mulx_u64(&x62, &x63, x54, 0xffffffff)
   declare
      T_62 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x62 := Unsigned_64 (T_62 and 16#FFFF_FFFF_FFFF_FFFF#);
      x63 := Unsigned_64 (Shift_Right (T_62, 64));
   end;

   --  mulx_u64(&x64, &x65, x54, 0xffffffffffffffff)
   declare
      T_64 : constant Unsigned_128 := Unsigned_128 (x54) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x64 := Unsigned_64 (T_64 and 16#FFFF_FFFF_FFFF_FFFF#);
      x65 := Unsigned_64 (Shift_Right (T_64, 64));
   end;

   --  addcarryx_u64(&x66, &x67, 0x0, x65, x62)
   declare
      T_66 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x65) + Unsigned_128 (x62);
   begin
      x66 := Unsigned_64 (T_66 and 16#FFFF_FFFF_FFFF_FFFF#);
      x67 := Unsigned_64 (Shift_Right (T_66, 64));
   end;

   --  addcarryx_u64(&x68, &x69, 0x0, x54, x64)
   declare
      T_68 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x54) + Unsigned_128 (x64);
   begin
      x68 := Unsigned_64 (T_68 and 16#FFFF_FFFF_FFFF_FFFF#);
      x69 := Unsigned_64 (Shift_Right (T_68, 64));
   end;

   --  addcarryx_u64(&x70, &x71, x69, x56, x66)
   declare
      T_70 : constant Unsigned_128 := Unsigned_128 (x69) + Unsigned_128 (x56) + Unsigned_128 (x66);
   begin
      x70 := Unsigned_64 (T_70 and 16#FFFF_FFFF_FFFF_FFFF#);
      x71 := Unsigned_64 (Shift_Right (T_70, 64));
   end;

   --  addcarryx_u64(&x72, &x73, x71, x58, (x67 + x63))
   declare
      T_72 : constant Unsigned_128 := Unsigned_128 (x71) + Unsigned_128 (x58) + Unsigned_128 (x67 + x63);
   begin
      x72 := Unsigned_64 (T_72 and 16#FFFF_FFFF_FFFF_FFFF#);
      x73 := Unsigned_64 (Shift_Right (T_72, 64));
   end;

   --  addcarryx_u64(&x74, &x75, x73, (x59 + (x53 + x39)), x60)
   declare
      T_74 : constant Unsigned_128 := Unsigned_128 (x73) + Unsigned_128 (x59 + (x53 + x39)) + Unsigned_128 (x60);
   begin
      x74 := Unsigned_64 (T_74 and 16#FFFF_FFFF_FFFF_FFFF#);
      x75 := Unsigned_64 (Shift_Right (T_74, 64));
   end;

   --  x76 = (x75 + x61)
   x76 := x75 + x61;

   --  Conditional subtraction of p
   --  subborrowx_u64(&x77, &x78, 0x0, x70, 0xffffffffffffffff)
   declare
      T_77 : constant Unsigned_128 := Unsigned_128 (x70) - Unsigned_128 (0) - Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x77 := Unsigned_64 (T_77 and 16#FFFF_FFFF_FFFF_FFFF#);
      x78 := Unsigned_64 (Shift_Right (T_77, 64)) and 1;
   end;

   --  subborrowx_u64(&x79, &x80, x78, x72, 0xffffffff)
   declare
      T_79 : constant Unsigned_128 := Unsigned_128 (x72) - Unsigned_128 (x78) - Unsigned_128 (16#FFFF_FFFF#);
   begin
      x79 := Unsigned_64 (T_79 and 16#FFFF_FFFF_FFFF_FFFF#);
      x80 := Unsigned_64 (Shift_Right (T_79, 64)) and 1;
   end;

   --  subborrowx_u64(&x81, &x82, x80, x74, 0x0)
   declare
      T_81 : constant Unsigned_128 := Unsigned_128 (x74) - Unsigned_128 (x80) - Unsigned_128 (0);
   begin
      x81 := Unsigned_64 (T_81 and 16#FFFF_FFFF_FFFF_FFFF#);
      x82 := Unsigned_64 (Shift_Right (T_81, 64)) and 1;
   end;

   --  subborrowx_u64(&x83, &x84, x82, x76, 0xffffffff00000001)
   declare
      T_83 : constant Unsigned_128 := Unsigned_128 (x76) - Unsigned_128 (x82) - Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x83 := Unsigned_64 (T_83 and 16#FFFF_FFFF_FFFF_FFFF#);
      x84 := Unsigned_64 (Shift_Right (T_83, 64)) and 1;
   end;

   --  subborrowx_u64(&x85, &x86, x84, 0x0, 0x0)
   declare
      T_85 : constant Unsigned_128 := Unsigned_128 (0) - Unsigned_128 (x84) - Unsigned_128 (0);
   begin
      x85 := Unsigned_64 (T_85 and 16#FFFF_FFFF_FFFF_FFFF#);
      x86 := Unsigned_64 (Shift_Right (T_85, 64)) and 1;
   end;

   --  cmovznz_u64(&x87, x86, x77, x70)
   declare
      Mask_87 : constant Unsigned_64 := -(x86 and 1);
   begin
      x87 := (Mask_87 and x70) or ((not Mask_87) and x77);
   end;

   --  cmovznz_u64(&x88, x86, x79, x72)
   declare
      Mask_88 : constant Unsigned_64 := -(x86 and 1);
   begin
      x88 := (Mask_88 and x72) or ((not Mask_88) and x79);
   end;

   --  cmovznz_u64(&x89, x86, x81, x74)
   declare
      Mask_89 : constant Unsigned_64 := -(x86 and 1);
   begin
      x89 := (Mask_89 and x74) or ((not Mask_89) and x81);
   end;

   --  cmovznz_u64(&x90, x86, x83, x76)
   declare
      Mask_90 : constant Unsigned_64 := -(x86 and 1);
   begin
      x90 := (Mask_90 and x76) or ((not Mask_90) and x83);
   end;

   Out1 := (x87, x88, x89, x90);
   return Out1;
end From_Montgomery;

------------------------------------------------------------------------

function To_Montgomery (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24 : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32 : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40 : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48 : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56 : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64 : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72 : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80 : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88 : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96 : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170 : Unsigned_64;
begin
   x1 := Arg1 (1);
   x2 := Arg1 (2);
   x3 := Arg1 (3);
   x4 := Arg1 (0);

   --  Round 1: multiply x4 by R^2 mod p constants
   --  mulx_u64(&x5, &x6, x4, 0x4fffffffd)
   declare
      T_5 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (16#4_FFFF_FFFD#);
   begin
      x5 := Unsigned_64 (T_5 and 16#FFFF_FFFF_FFFF_FFFF#);
      x6 := Unsigned_64 (Shift_Right (T_5, 64));
   end;

   --  mulx_u64(&x7, &x8, x4, 0xfffffffffffffffe)
   declare
      T_7 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFE#);
   begin
      x7 := Unsigned_64 (T_7 and 16#FFFF_FFFF_FFFF_FFFF#);
      x8 := Unsigned_64 (Shift_Right (T_7, 64));
   end;

   --  mulx_u64(&x9, &x10, x4, 0xfffffffbffffffff)
   declare
      T_9 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (16#FFFF_FFFB_FFFF_FFFF#);
   begin
      x9 := Unsigned_64 (T_9 and 16#FFFF_FFFF_FFFF_FFFF#);
      x10 := Unsigned_64 (Shift_Right (T_9, 64));
   end;

   --  mulx_u64(&x11, &x12, x4, 0x3)
   declare
      T_11 : constant Unsigned_128 := Unsigned_128 (x4) * Unsigned_128 (16#3#);
   begin
      x11 := Unsigned_64 (T_11 and 16#FFFF_FFFF_FFFF_FFFF#);
      x12 := Unsigned_64 (Shift_Right (T_11, 64));
   end;

   --  addcarryx_u64(&x13, &x14, 0x0, x12, x9)
   declare
      T_13 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x12) + Unsigned_128 (x9);
   begin
      x13 := Unsigned_64 (T_13 and 16#FFFF_FFFF_FFFF_FFFF#);
      x14 := Unsigned_64 (Shift_Right (T_13, 64));
   end;

   --  addcarryx_u64(&x15, &x16, x14, x10, x7)
   declare
      T_15 : constant Unsigned_128 := Unsigned_128 (x14) + Unsigned_128 (x10) + Unsigned_128 (x7);
   begin
      x15 := Unsigned_64 (T_15 and 16#FFFF_FFFF_FFFF_FFFF#);
      x16 := Unsigned_64 (Shift_Right (T_15, 64));
   end;

   --  addcarryx_u64(&x17, &x18, x16, x8, x5)
   declare
      T_17 : constant Unsigned_128 := Unsigned_128 (x16) + Unsigned_128 (x8) + Unsigned_128 (x5);
   begin
      x17 := Unsigned_64 (T_17 and 16#FFFF_FFFF_FFFF_FFFF#);
      x18 := Unsigned_64 (Shift_Right (T_17, 64));
   end;

   --  Montgomery reduction round 1
   --  mulx_u64(&x19, &x20, x11, 0xffffffff00000001)
   declare
      T_19 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x19 := Unsigned_64 (T_19 and 16#FFFF_FFFF_FFFF_FFFF#);
      x20 := Unsigned_64 (Shift_Right (T_19, 64));
   end;

   --  mulx_u64(&x21, &x22, x11, 0xffffffff)
   declare
      T_21 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x21 := Unsigned_64 (T_21 and 16#FFFF_FFFF_FFFF_FFFF#);
      x22 := Unsigned_64 (Shift_Right (T_21, 64));
   end;

   --  mulx_u64(&x23, &x24, x11, 0xffffffffffffffff)
   declare
      T_23 : constant Unsigned_128 := Unsigned_128 (x11) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x23 := Unsigned_64 (T_23 and 16#FFFF_FFFF_FFFF_FFFF#);
      x24 := Unsigned_64 (Shift_Right (T_23, 64));
   end;

   --  addcarryx_u64(&x25, &x26, 0x0, x24, x21)
   declare
      T_25 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x24) + Unsigned_128 (x21);
   begin
      x25 := Unsigned_64 (T_25 and 16#FFFF_FFFF_FFFF_FFFF#);
      x26 := Unsigned_64 (Shift_Right (T_25, 64));
   end;

   --  addcarryx_u64(&x27, &x28, 0x0, x11, x23)
   declare
      T_27 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x11) + Unsigned_128 (x23);
   begin
      x27 := Unsigned_64 (T_27 and 16#FFFF_FFFF_FFFF_FFFF#);
      x28 := Unsigned_64 (Shift_Right (T_27, 64));
   end;

   --  addcarryx_u64(&x29, &x30, x28, x13, x25)
   declare
      T_29 : constant Unsigned_128 := Unsigned_128 (x28) + Unsigned_128 (x13) + Unsigned_128 (x25);
   begin
      x29 := Unsigned_64 (T_29 and 16#FFFF_FFFF_FFFF_FFFF#);
      x30 := Unsigned_64 (Shift_Right (T_29, 64));
   end;

   --  addcarryx_u64(&x31, &x32, x30, x15, (x26 + x22))
   declare
      T_31 : constant Unsigned_128 := Unsigned_128 (x30) + Unsigned_128 (x15) + Unsigned_128 (x26 + x22);
   begin
      x31 := Unsigned_64 (T_31 and 16#FFFF_FFFF_FFFF_FFFF#);
      x32 := Unsigned_64 (Shift_Right (T_31, 64));
   end;

   --  addcarryx_u64(&x33, &x34, x32, x17, x19)
   declare
      T_33 : constant Unsigned_128 := Unsigned_128 (x32) + Unsigned_128 (x17) + Unsigned_128 (x19);
   begin
      x33 := Unsigned_64 (T_33 and 16#FFFF_FFFF_FFFF_FFFF#);
      x34 := Unsigned_64 (Shift_Right (T_33, 64));
   end;

   --  addcarryx_u64(&x35, &x36, x34, (x18 + x6), x20)
   declare
      T_35 : constant Unsigned_128 := Unsigned_128 (x34) + Unsigned_128 (x18 + x6) + Unsigned_128 (x20);
   begin
      x35 := Unsigned_64 (T_35 and 16#FFFF_FFFF_FFFF_FFFF#);
      x36 := Unsigned_64 (Shift_Right (T_35, 64));
   end;

   --  Round 2: multiply x1 by R^2 mod p constants
   --  mulx_u64(&x37, &x38, x1, 0x4fffffffd)
   declare
      T_37 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#4_FFFF_FFFD#);
   begin
      x37 := Unsigned_64 (T_37 and 16#FFFF_FFFF_FFFF_FFFF#);
      x38 := Unsigned_64 (Shift_Right (T_37, 64));
   end;

   --  mulx_u64(&x39, &x40, x1, 0xfffffffffffffffe)
   declare
      T_39 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFE#);
   begin
      x39 := Unsigned_64 (T_39 and 16#FFFF_FFFF_FFFF_FFFF#);
      x40 := Unsigned_64 (Shift_Right (T_39, 64));
   end;

   --  mulx_u64(&x41, &x42, x1, 0xfffffffbffffffff)
   declare
      T_41 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#FFFF_FFFB_FFFF_FFFF#);
   begin
      x41 := Unsigned_64 (T_41 and 16#FFFF_FFFF_FFFF_FFFF#);
      x42 := Unsigned_64 (Shift_Right (T_41, 64));
   end;

   --  mulx_u64(&x43, &x44, x1, 0x3)
   declare
      T_43 : constant Unsigned_128 := Unsigned_128 (x1) * Unsigned_128 (16#3#);
   begin
      x43 := Unsigned_64 (T_43 and 16#FFFF_FFFF_FFFF_FFFF#);
      x44 := Unsigned_64 (Shift_Right (T_43, 64));
   end;

   --  addcarryx_u64(&x45, &x46, 0x0, x44, x41)
   declare
      T_45 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x44) + Unsigned_128 (x41);
   begin
      x45 := Unsigned_64 (T_45 and 16#FFFF_FFFF_FFFF_FFFF#);
      x46 := Unsigned_64 (Shift_Right (T_45, 64));
   end;

   --  addcarryx_u64(&x47, &x48, x46, x42, x39)
   declare
      T_47 : constant Unsigned_128 := Unsigned_128 (x46) + Unsigned_128 (x42) + Unsigned_128 (x39);
   begin
      x47 := Unsigned_64 (T_47 and 16#FFFF_FFFF_FFFF_FFFF#);
      x48 := Unsigned_64 (Shift_Right (T_47, 64));
   end;

   --  addcarryx_u64(&x49, &x50, x48, x40, x37)
   declare
      T_49 : constant Unsigned_128 := Unsigned_128 (x48) + Unsigned_128 (x40) + Unsigned_128 (x37);
   begin
      x49 := Unsigned_64 (T_49 and 16#FFFF_FFFF_FFFF_FFFF#);
      x50 := Unsigned_64 (Shift_Right (T_49, 64));
   end;

   --  addcarryx_u64(&x51, &x52, 0x0, x29, x43)
   declare
      T_51 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x29) + Unsigned_128 (x43);
   begin
      x51 := Unsigned_64 (T_51 and 16#FFFF_FFFF_FFFF_FFFF#);
      x52 := Unsigned_64 (Shift_Right (T_51, 64));
   end;

   --  addcarryx_u64(&x53, &x54, x52, x31, x45)
   declare
      T_53 : constant Unsigned_128 := Unsigned_128 (x52) + Unsigned_128 (x31) + Unsigned_128 (x45);
   begin
      x53 := Unsigned_64 (T_53 and 16#FFFF_FFFF_FFFF_FFFF#);
      x54 := Unsigned_64 (Shift_Right (T_53, 64));
   end;

   --  addcarryx_u64(&x55, &x56, x54, x33, x47)
   declare
      T_55 : constant Unsigned_128 := Unsigned_128 (x54) + Unsigned_128 (x33) + Unsigned_128 (x47);
   begin
      x55 := Unsigned_64 (T_55 and 16#FFFF_FFFF_FFFF_FFFF#);
      x56 := Unsigned_64 (Shift_Right (T_55, 64));
   end;

   --  addcarryx_u64(&x57, &x58, x56, x35, x49)
   declare
      T_57 : constant Unsigned_128 := Unsigned_128 (x56) + Unsigned_128 (x35) + Unsigned_128 (x49);
   begin
      x57 := Unsigned_64 (T_57 and 16#FFFF_FFFF_FFFF_FFFF#);
      x58 := Unsigned_64 (Shift_Right (T_57, 64));
   end;

   --  Montgomery reduction round 2
   --  mulx_u64(&x59, &x60, x51, 0xffffffff00000001)
   declare
      T_59 : constant Unsigned_128 := Unsigned_128 (x51) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x59 := Unsigned_64 (T_59 and 16#FFFF_FFFF_FFFF_FFFF#);
      x60 := Unsigned_64 (Shift_Right (T_59, 64));
   end;

   --  mulx_u64(&x61, &x62, x51, 0xffffffff)
   declare
      T_61 : constant Unsigned_128 := Unsigned_128 (x51) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x61 := Unsigned_64 (T_61 and 16#FFFF_FFFF_FFFF_FFFF#);
      x62 := Unsigned_64 (Shift_Right (T_61, 64));
   end;

   --  mulx_u64(&x63, &x64, x51, 0xffffffffffffffff)
   declare
      T_63 : constant Unsigned_128 := Unsigned_128 (x51) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x63 := Unsigned_64 (T_63 and 16#FFFF_FFFF_FFFF_FFFF#);
      x64 := Unsigned_64 (Shift_Right (T_63, 64));
   end;

   --  addcarryx_u64(&x65, &x66, 0x0, x64, x61)
   declare
      T_65 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x64) + Unsigned_128 (x61);
   begin
      x65 := Unsigned_64 (T_65 and 16#FFFF_FFFF_FFFF_FFFF#);
      x66 := Unsigned_64 (Shift_Right (T_65, 64));
   end;

   --  addcarryx_u64(&x67, &x68, 0x0, x51, x63)
   declare
      T_67 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x51) + Unsigned_128 (x63);
   begin
      x67 := Unsigned_64 (T_67 and 16#FFFF_FFFF_FFFF_FFFF#);
      x68 := Unsigned_64 (Shift_Right (T_67, 64));
   end;

   --  addcarryx_u64(&x69, &x70, x68, x53, x65)
   declare
      T_69 : constant Unsigned_128 := Unsigned_128 (x68) + Unsigned_128 (x53) + Unsigned_128 (x65);
   begin
      x69 := Unsigned_64 (T_69 and 16#FFFF_FFFF_FFFF_FFFF#);
      x70 := Unsigned_64 (Shift_Right (T_69, 64));
   end;

   --  addcarryx_u64(&x71, &x72, x70, x55, (x66 + x62))
   declare
      T_71 : constant Unsigned_128 := Unsigned_128 (x70) + Unsigned_128 (x55) + Unsigned_128 (x66 + x62);
   begin
      x71 := Unsigned_64 (T_71 and 16#FFFF_FFFF_FFFF_FFFF#);
      x72 := Unsigned_64 (Shift_Right (T_71, 64));
   end;

   --  addcarryx_u64(&x73, &x74, x72, x57, x59)
   declare
      T_73 : constant Unsigned_128 := Unsigned_128 (x72) + Unsigned_128 (x57) + Unsigned_128 (x59);
   begin
      x73 := Unsigned_64 (T_73 and 16#FFFF_FFFF_FFFF_FFFF#);
      x74 := Unsigned_64 (Shift_Right (T_73, 64));
   end;

   --  addcarryx_u64(&x75, &x76, x74, (((uint64_t)x58 + x36) + (x50 + x38)), x60)
   declare
      T_75 : constant Unsigned_128 := Unsigned_128 (x74) + Unsigned_128 ((x58 + x36) + (x50 + x38)) + Unsigned_128 (x60);
   begin
      x75 := Unsigned_64 (T_75 and 16#FFFF_FFFF_FFFF_FFFF#);
      x76 := Unsigned_64 (Shift_Right (T_75, 64));
   end;

   --  Round 3: multiply x2 by R^2 mod p constants
   --  mulx_u64(&x77, &x78, x2, 0x4fffffffd)
   declare
      T_77 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (16#4_FFFF_FFFD#);
   begin
      x77 := Unsigned_64 (T_77 and 16#FFFF_FFFF_FFFF_FFFF#);
      x78 := Unsigned_64 (Shift_Right (T_77, 64));
   end;

   --  mulx_u64(&x79, &x80, x2, 0xfffffffffffffffe)
   declare
      T_79 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFE#);
   begin
      x79 := Unsigned_64 (T_79 and 16#FFFF_FFFF_FFFF_FFFF#);
      x80 := Unsigned_64 (Shift_Right (T_79, 64));
   end;

   --  mulx_u64(&x81, &x82, x2, 0xfffffffbffffffff)
   declare
      T_81 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (16#FFFF_FFFB_FFFF_FFFF#);
   begin
      x81 := Unsigned_64 (T_81 and 16#FFFF_FFFF_FFFF_FFFF#);
      x82 := Unsigned_64 (Shift_Right (T_81, 64));
   end;

   --  mulx_u64(&x83, &x84, x2, 0x3)
   declare
      T_83 : constant Unsigned_128 := Unsigned_128 (x2) * Unsigned_128 (16#3#);
   begin
      x83 := Unsigned_64 (T_83 and 16#FFFF_FFFF_FFFF_FFFF#);
      x84 := Unsigned_64 (Shift_Right (T_83, 64));
   end;

   --  addcarryx_u64(&x85, &x86, 0x0, x84, x81)
   declare
      T_85 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x84) + Unsigned_128 (x81);
   begin
      x85 := Unsigned_64 (T_85 and 16#FFFF_FFFF_FFFF_FFFF#);
      x86 := Unsigned_64 (Shift_Right (T_85, 64));
   end;

   --  addcarryx_u64(&x87, &x88, x86, x82, x79)
   declare
      T_87 : constant Unsigned_128 := Unsigned_128 (x86) + Unsigned_128 (x82) + Unsigned_128 (x79);
   begin
      x87 := Unsigned_64 (T_87 and 16#FFFF_FFFF_FFFF_FFFF#);
      x88 := Unsigned_64 (Shift_Right (T_87, 64));
   end;

   --  addcarryx_u64(&x89, &x90, x88, x80, x77)
   declare
      T_89 : constant Unsigned_128 := Unsigned_128 (x88) + Unsigned_128 (x80) + Unsigned_128 (x77);
   begin
      x89 := Unsigned_64 (T_89 and 16#FFFF_FFFF_FFFF_FFFF#);
      x90 := Unsigned_64 (Shift_Right (T_89, 64));
   end;

   --  addcarryx_u64(&x91, &x92, 0x0, x69, x83)
   declare
      T_91 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x69) + Unsigned_128 (x83);
   begin
      x91 := Unsigned_64 (T_91 and 16#FFFF_FFFF_FFFF_FFFF#);
      x92 := Unsigned_64 (Shift_Right (T_91, 64));
   end;

   --  addcarryx_u64(&x93, &x94, x92, x71, x85)
   declare
      T_93 : constant Unsigned_128 := Unsigned_128 (x92) + Unsigned_128 (x71) + Unsigned_128 (x85);
   begin
      x93 := Unsigned_64 (T_93 and 16#FFFF_FFFF_FFFF_FFFF#);
      x94 := Unsigned_64 (Shift_Right (T_93, 64));
   end;

   --  addcarryx_u64(&x95, &x96, x94, x73, x87)
   declare
      T_95 : constant Unsigned_128 := Unsigned_128 (x94) + Unsigned_128 (x73) + Unsigned_128 (x87);
   begin
      x95 := Unsigned_64 (T_95 and 16#FFFF_FFFF_FFFF_FFFF#);
      x96 := Unsigned_64 (Shift_Right (T_95, 64));
   end;

   --  addcarryx_u64(&x97, &x98, x96, x75, x89)
   declare
      T_97 : constant Unsigned_128 := Unsigned_128 (x96) + Unsigned_128 (x75) + Unsigned_128 (x89);
   begin
      x97 := Unsigned_64 (T_97 and 16#FFFF_FFFF_FFFF_FFFF#);
      x98 := Unsigned_64 (Shift_Right (T_97, 64));
   end;

   --  Montgomery reduction round 3
   --  mulx_u64(&x99, &x100, x91, 0xffffffff00000001)
   declare
      T_99 : constant Unsigned_128 := Unsigned_128 (x91) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x99 := Unsigned_64 (T_99 and 16#FFFF_FFFF_FFFF_FFFF#);
      x100 := Unsigned_64 (Shift_Right (T_99, 64));
   end;

   --  mulx_u64(&x101, &x102, x91, 0xffffffff)
   declare
      T_101 : constant Unsigned_128 := Unsigned_128 (x91) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x101 := Unsigned_64 (T_101 and 16#FFFF_FFFF_FFFF_FFFF#);
      x102 := Unsigned_64 (Shift_Right (T_101, 64));
   end;

   --  mulx_u64(&x103, &x104, x91, 0xffffffffffffffff)
   declare
      T_103 : constant Unsigned_128 := Unsigned_128 (x91) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x103 := Unsigned_64 (T_103 and 16#FFFF_FFFF_FFFF_FFFF#);
      x104 := Unsigned_64 (Shift_Right (T_103, 64));
   end;

   --  addcarryx_u64(&x105, &x106, 0x0, x104, x101)
   declare
      T_105 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x104) + Unsigned_128 (x101);
   begin
      x105 := Unsigned_64 (T_105 and 16#FFFF_FFFF_FFFF_FFFF#);
      x106 := Unsigned_64 (Shift_Right (T_105, 64));
   end;

   --  addcarryx_u64(&x107, &x108, 0x0, x91, x103)
   declare
      T_107 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x91) + Unsigned_128 (x103);
   begin
      x107 := Unsigned_64 (T_107 and 16#FFFF_FFFF_FFFF_FFFF#);
      x108 := Unsigned_64 (Shift_Right (T_107, 64));
   end;

   --  addcarryx_u64(&x109, &x110, x108, x93, x105)
   declare
      T_109 : constant Unsigned_128 := Unsigned_128 (x108) + Unsigned_128 (x93) + Unsigned_128 (x105);
   begin
      x109 := Unsigned_64 (T_109 and 16#FFFF_FFFF_FFFF_FFFF#);
      x110 := Unsigned_64 (Shift_Right (T_109, 64));
   end;

   --  addcarryx_u64(&x111, &x112, x110, x95, (x106 + x102))
   declare
      T_111 : constant Unsigned_128 := Unsigned_128 (x110) + Unsigned_128 (x95) + Unsigned_128 (x106 + x102);
   begin
      x111 := Unsigned_64 (T_111 and 16#FFFF_FFFF_FFFF_FFFF#);
      x112 := Unsigned_64 (Shift_Right (T_111, 64));
   end;

   --  addcarryx_u64(&x113, &x114, x112, x97, x99)
   declare
      T_113 : constant Unsigned_128 := Unsigned_128 (x112) + Unsigned_128 (x97) + Unsigned_128 (x99);
   begin
      x113 := Unsigned_64 (T_113 and 16#FFFF_FFFF_FFFF_FFFF#);
      x114 := Unsigned_64 (Shift_Right (T_113, 64));
   end;

   --  addcarryx_u64(&x115, &x116, x114, (((uint64_t)x98 + x76) + (x90 + x78)), x100)
   declare
      T_115 : constant Unsigned_128 := Unsigned_128 (x114) + Unsigned_128 ((x98 + x76) + (x90 + x78)) + Unsigned_128 (x100);
   begin
      x115 := Unsigned_64 (T_115 and 16#FFFF_FFFF_FFFF_FFFF#);
      x116 := Unsigned_64 (Shift_Right (T_115, 64));
   end;

   --  Round 4: multiply x3 by R^2 mod p constants
   --  mulx_u64(&x117, &x118, x3, 0x4fffffffd)
   declare
      T_117 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (16#4_FFFF_FFFD#);
   begin
      x117 := Unsigned_64 (T_117 and 16#FFFF_FFFF_FFFF_FFFF#);
      x118 := Unsigned_64 (Shift_Right (T_117, 64));
   end;

   --  mulx_u64(&x119, &x120, x3, 0xfffffffffffffffe)
   declare
      T_119 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFE#);
   begin
      x119 := Unsigned_64 (T_119 and 16#FFFF_FFFF_FFFF_FFFF#);
      x120 := Unsigned_64 (Shift_Right (T_119, 64));
   end;

   --  mulx_u64(&x121, &x122, x3, 0xfffffffbffffffff)
   declare
      T_121 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (16#FFFF_FFFB_FFFF_FFFF#);
   begin
      x121 := Unsigned_64 (T_121 and 16#FFFF_FFFF_FFFF_FFFF#);
      x122 := Unsigned_64 (Shift_Right (T_121, 64));
   end;

   --  mulx_u64(&x123, &x124, x3, 0x3)
   declare
      T_123 : constant Unsigned_128 := Unsigned_128 (x3) * Unsigned_128 (16#3#);
   begin
      x123 := Unsigned_64 (T_123 and 16#FFFF_FFFF_FFFF_FFFF#);
      x124 := Unsigned_64 (Shift_Right (T_123, 64));
   end;

   --  addcarryx_u64(&x125, &x126, 0x0, x124, x121)
   declare
      T_125 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x124) + Unsigned_128 (x121);
   begin
      x125 := Unsigned_64 (T_125 and 16#FFFF_FFFF_FFFF_FFFF#);
      x126 := Unsigned_64 (Shift_Right (T_125, 64));
   end;

   --  addcarryx_u64(&x127, &x128, x126, x122, x119)
   declare
      T_127 : constant Unsigned_128 := Unsigned_128 (x126) + Unsigned_128 (x122) + Unsigned_128 (x119);
   begin
      x127 := Unsigned_64 (T_127 and 16#FFFF_FFFF_FFFF_FFFF#);
      x128 := Unsigned_64 (Shift_Right (T_127, 64));
   end;

   --  addcarryx_u64(&x129, &x130, x128, x120, x117)
   declare
      T_129 : constant Unsigned_128 := Unsigned_128 (x128) + Unsigned_128 (x120) + Unsigned_128 (x117);
   begin
      x129 := Unsigned_64 (T_129 and 16#FFFF_FFFF_FFFF_FFFF#);
      x130 := Unsigned_64 (Shift_Right (T_129, 64));
   end;

   --  addcarryx_u64(&x131, &x132, 0x0, x109, x123)
   declare
      T_131 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x109) + Unsigned_128 (x123);
   begin
      x131 := Unsigned_64 (T_131 and 16#FFFF_FFFF_FFFF_FFFF#);
      x132 := Unsigned_64 (Shift_Right (T_131, 64));
   end;

   --  addcarryx_u64(&x133, &x134, x132, x111, x125)
   declare
      T_133 : constant Unsigned_128 := Unsigned_128 (x132) + Unsigned_128 (x111) + Unsigned_128 (x125);
   begin
      x133 := Unsigned_64 (T_133 and 16#FFFF_FFFF_FFFF_FFFF#);
      x134 := Unsigned_64 (Shift_Right (T_133, 64));
   end;

   --  addcarryx_u64(&x135, &x136, x134, x113, x127)
   declare
      T_135 : constant Unsigned_128 := Unsigned_128 (x134) + Unsigned_128 (x113) + Unsigned_128 (x127);
   begin
      x135 := Unsigned_64 (T_135 and 16#FFFF_FFFF_FFFF_FFFF#);
      x136 := Unsigned_64 (Shift_Right (T_135, 64));
   end;

   --  addcarryx_u64(&x137, &x138, x136, x115, x129)
   declare
      T_137 : constant Unsigned_128 := Unsigned_128 (x136) + Unsigned_128 (x115) + Unsigned_128 (x129);
   begin
      x137 := Unsigned_64 (T_137 and 16#FFFF_FFFF_FFFF_FFFF#);
      x138 := Unsigned_64 (Shift_Right (T_137, 64));
   end;

   --  Montgomery reduction round 4
   --  mulx_u64(&x139, &x140, x131, 0xffffffff00000001)
   declare
      T_139 : constant Unsigned_128 := Unsigned_128 (x131) * Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x139 := Unsigned_64 (T_139 and 16#FFFF_FFFF_FFFF_FFFF#);
      x140 := Unsigned_64 (Shift_Right (T_139, 64));
   end;

   --  mulx_u64(&x141, &x142, x131, 0xffffffff)
   declare
      T_141 : constant Unsigned_128 := Unsigned_128 (x131) * Unsigned_128 (16#FFFF_FFFF#);
   begin
      x141 := Unsigned_64 (T_141 and 16#FFFF_FFFF_FFFF_FFFF#);
      x142 := Unsigned_64 (Shift_Right (T_141, 64));
   end;

   --  mulx_u64(&x143, &x144, x131, 0xffffffffffffffff)
   declare
      T_143 : constant Unsigned_128 := Unsigned_128 (x131) * Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x143 := Unsigned_64 (T_143 and 16#FFFF_FFFF_FFFF_FFFF#);
      x144 := Unsigned_64 (Shift_Right (T_143, 64));
   end;

   --  addcarryx_u64(&x145, &x146, 0x0, x144, x141)
   declare
      T_145 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x144) + Unsigned_128 (x141);
   begin
      x145 := Unsigned_64 (T_145 and 16#FFFF_FFFF_FFFF_FFFF#);
      x146 := Unsigned_64 (Shift_Right (T_145, 64));
   end;

   --  addcarryx_u64(&x147, &x148, 0x0, x131, x143)
   declare
      T_147 : constant Unsigned_128 := Unsigned_128 (0) + Unsigned_128 (x131) + Unsigned_128 (x143);
   begin
      x147 := Unsigned_64 (T_147 and 16#FFFF_FFFF_FFFF_FFFF#);
      x148 := Unsigned_64 (Shift_Right (T_147, 64));
   end;

   --  addcarryx_u64(&x149, &x150, x148, x133, x145)
   declare
      T_149 : constant Unsigned_128 := Unsigned_128 (x148) + Unsigned_128 (x133) + Unsigned_128 (x145);
   begin
      x149 := Unsigned_64 (T_149 and 16#FFFF_FFFF_FFFF_FFFF#);
      x150 := Unsigned_64 (Shift_Right (T_149, 64));
   end;

   --  addcarryx_u64(&x151, &x152, x150, x135, (x146 + x142))
   declare
      T_151 : constant Unsigned_128 := Unsigned_128 (x150) + Unsigned_128 (x135) + Unsigned_128 (x146 + x142);
   begin
      x151 := Unsigned_64 (T_151 and 16#FFFF_FFFF_FFFF_FFFF#);
      x152 := Unsigned_64 (Shift_Right (T_151, 64));
   end;

   --  addcarryx_u64(&x153, &x154, x152, x137, x139)
   declare
      T_153 : constant Unsigned_128 := Unsigned_128 (x152) + Unsigned_128 (x137) + Unsigned_128 (x139);
   begin
      x153 := Unsigned_64 (T_153 and 16#FFFF_FFFF_FFFF_FFFF#);
      x154 := Unsigned_64 (Shift_Right (T_153, 64));
   end;

   --  addcarryx_u64(&x155, &x156, x154, (((uint64_t)x138 + x116) + (x130 + x118)), x140)
   declare
      T_155 : constant Unsigned_128 := Unsigned_128 (x154) + Unsigned_128 ((x138 + x116) + (x130 + x118)) + Unsigned_128 (x140);
   begin
      x155 := Unsigned_64 (T_155 and 16#FFFF_FFFF_FFFF_FFFF#);
      x156 := Unsigned_64 (Shift_Right (T_155, 64));
   end;

   --  Conditional subtraction of p
   --  subborrowx_u64(&x157, &x158, 0x0, x149, 0xffffffffffffffff)
   declare
      T_157 : constant Unsigned_128 := Unsigned_128 (x149) - Unsigned_128 (0) - Unsigned_128 (16#FFFF_FFFF_FFFF_FFFF#);
   begin
      x157 := Unsigned_64 (T_157 and 16#FFFF_FFFF_FFFF_FFFF#);
      x158 := Unsigned_64 (Shift_Right (T_157, 64)) and 1;
   end;

   --  subborrowx_u64(&x159, &x160, x158, x151, 0xffffffff)
   declare
      T_159 : constant Unsigned_128 := Unsigned_128 (x151) - Unsigned_128 (x158) - Unsigned_128 (16#FFFF_FFFF#);
   begin
      x159 := Unsigned_64 (T_159 and 16#FFFF_FFFF_FFFF_FFFF#);
      x160 := Unsigned_64 (Shift_Right (T_159, 64)) and 1;
   end;

   --  subborrowx_u64(&x161, &x162, x160, x153, 0x0)
   declare
      T_161 : constant Unsigned_128 := Unsigned_128 (x153) - Unsigned_128 (x160) - Unsigned_128 (0);
   begin
      x161 := Unsigned_64 (T_161 and 16#FFFF_FFFF_FFFF_FFFF#);
      x162 := Unsigned_64 (Shift_Right (T_161, 64)) and 1;
   end;

   --  subborrowx_u64(&x163, &x164, x162, x155, 0xffffffff00000001)
   declare
      T_163 : constant Unsigned_128 := Unsigned_128 (x155) - Unsigned_128 (x162) - Unsigned_128 (16#FFFF_FFFF_0000_0001#);
   begin
      x163 := Unsigned_64 (T_163 and 16#FFFF_FFFF_FFFF_FFFF#);
      x164 := Unsigned_64 (Shift_Right (T_163, 64)) and 1;
   end;

   --  subborrowx_u64(&x165, &x166, x164, x156, 0x0)
   declare
      T_165 : constant Unsigned_128 := Unsigned_128 (x156) - Unsigned_128 (x164) - Unsigned_128 (0);
   begin
      x165 := Unsigned_64 (T_165 and 16#FFFF_FFFF_FFFF_FFFF#);
      x166 := Unsigned_64 (Shift_Right (T_165, 64)) and 1;
   end;

   --  cmovznz_u64(&x167, x166, x157, x149)
   declare
      Mask_167 : constant Unsigned_64 := -(x166 and 1);
   begin
      x167 := (Mask_167 and x149) or ((not Mask_167) and x157);
   end;

   --  cmovznz_u64(&x168, x166, x159, x151)
   declare
      Mask_168 : constant Unsigned_64 := -(x166 and 1);
   begin
      x168 := (Mask_168 and x151) or ((not Mask_168) and x159);
   end;

   --  cmovznz_u64(&x169, x166, x161, x153)
   declare
      Mask_169 : constant Unsigned_64 := -(x166 and 1);
   begin
      x169 := (Mask_169 and x153) or ((not Mask_169) and x161);
   end;

   --  cmovznz_u64(&x170, x166, x163, x155)
   declare
      Mask_170 : constant Unsigned_64 := -(x166 and 1);
   begin
      x170 := (Mask_170 and x155) or ((not Mask_170) and x163);
   end;

   Out1 := (x167, x168, x169, x170);
   return Out1;
end To_Montgomery;

end SPARKTLS.Fiat_P256;
