--  SPARKTLS.Revocation against the OpenSSL fixtures generated by
--  ../sparkx509/tests/revocation/gen.sh (default dir
--  /tmp/sparkx509-revocation, override with SPARKTLS_REVOCATION_FIXTURES).
--  Exercises the OCSP verdicts (good / revoked, CA-signed / delegated,
--  byName / byKey, SHA-1 / SHA-256 CertID, SHA-1 policy, tampering,
--  freshness) and the CRL verdicts (hit / miss / empty / tampered /
--  foreign issuer).

with Ada.Text_IO;      use Ada.Text_IO;
with Ada.Directories;
with Ada.Environment_Variables;
with Ada.Streams;
with Ada.Streams.Stream_IO;
with Interfaces;
with X509;
with X509.CRL;
with SPARKTLS;            use SPARKTLS;
with SPARKTLS.Revocation; use SPARKTLS.Revocation;

procedure Test_Revocation is
   use type Interfaces.Unsigned_8;
   use type Interfaces.Unsigned_32;

   Pass : Natural := 0;
   Fail : Natural := 0;

   procedure Check (Name : String; OK : Boolean) is
   begin
      if OK then
         Pass := Pass + 1;
         Put_Line ("PASS: " & Name);
      else
         Fail := Fail + 1;
         Put_Line ("FAIL: " & Name);
      end if;
   end Check;

   Dir : constant String :=
     (if Ada.Environment_Variables.Exists ("SPARKTLS_REVOCATION_FIXTURES")
      then Ada.Environment_Variables.Value ("SPARKTLS_REVOCATION_FIXTURES")
      else "/tmp/sparkx509-revocation");

   function Load (Name : String) return X509.Byte_Seq is
      package SIO renames Ada.Streams.Stream_IO;
      File : SIO.File_Type;
   begin
      SIO.Open (File, SIO.In_File, Dir & "/" & Name);
      declare
         Size : constant Natural := Natural (SIO.Size (File));
         Raw  : Ada.Streams.Stream_Element_Array
           (1 .. Ada.Streams.Stream_Element_Offset (Size));
         Last : Ada.Streams.Stream_Element_Offset;
         DER  : X509.Byte_Seq (0 .. X509.N32 (Size - 1));
      begin
         SIO.Read (File, Raw, Last);
         SIO.Close (File);
         for I in DER'Range loop
            DER (I) := X509.Byte (Raw (Ada.Streams.Stream_Element_Offset (I + 1)));
         end loop;
         return DER;
      end;
   end Load;

   --  Fixture clock. gen.sh regenerates the OCSP responses / CRLs with the
   --  real time of day (openssl stamps thisUpdate = now, nextUpdate = +7 d),
   --  so a pinned constant here goes stale or lands "in the future" the
   --  moment the fixtures are rebuilt. gen.sh therefore also writes
   --  now.txt: line 1 = generation + 1 h (our "Now"), line 2 = generation
   --  + 30 d (our "Future", past every nextUpdate). Read those; fall back
   --  to the original constants only if the file is missing.
   function Fixture_Time
     (Line_No : Positive; Default : X509.Date_Time) return X509.Date_Time
   is
      F : File_Type;
      V : array (1 .. 6) of Natural := (others => 0);
   begin
      Open (F, In_File, Dir & "/now.txt");
      declare
         S   : String (1 .. 256);
         L   : Natural := 0;
         P   : Natural := 1;
         Beg : Natural;
      begin
         for N in 1 .. Line_No loop
            Get_Line (F, S, L);
         end loop;
         Close (F);
         for K in 1 .. 6 loop
            while P <= L and then S (P) = ' ' loop
               P := P + 1;
            end loop;
            Beg := P;
            while P <= L and then S (P) /= ' ' loop
               P := P + 1;
            end loop;
            V (K) := Natural'Value (S (Beg .. P - 1));
         end loop;
      end;
      return (V (1), V (2), V (3), V (4), V (5), V (6));
   exception
      when others =>
         if Is_Open (F) then
            Close (F);
         end if;
         Put_Line ("NOTE: " & Dir & "/now.txt missing or unreadable;"
                   & " using the built-in fixture clock");
         return Default;
   end Fixture_Time;

   Now    : constant X509.Date_Time := Fixture_Time (1, (2026, 9, 10, 12, 0, 0));
   Future : constant X509.Date_Time := Fixture_Time (2, (2027, 1, 1, 0, 0, 0));

   Skew : constant := 300;

   procedure OCSP_Case
     (Name       : String;
      Leaf_File  : String;
      Resp_File  : String;
      Expect     : Revocation_Result;
      Allow_SHA1 : Boolean := True;
      At_Time    : X509.Date_Time := Now;
      Tamper     : Boolean := False;
      Issuer_File : String := "ca.der")
   is
      Leaf_DER   : constant X509.Byte_Seq := Load (Leaf_File);
      Issuer_DER : constant X509.Byte_Seq := Load (Issuer_File);
      Resp       : X509.Byte_Seq := Load (Resp_File);
      Leaf, Issuer : X509.Certificate;
      OK1, OK2   : Boolean;
      R          : Revocation_Result;
   begin
      X509.Parse (Leaf_DER, Leaf, OK1);
      X509.Parse (Issuer_DER, Issuer, OK2);
      if not (OK1 and OK2) then
         Check (Name & " (fixture parse)", False);
         return;
      end if;
      if Tamper then
         --  Flip a byte early in tbsResponseData (offset 40 lands in the
         --  responderID / producedAt of every fixture): the signature no
         --  longer verifies and the response must be Rev_Malformed. (The
         --  midpoint of the DER is inside the embedded certificate, which
         --  the signature does not cover.)
         Resp (40) := Resp (40) xor 16#01#;
      end if;
      Check_Stapled_OCSP (Leaf_DER, Leaf, Issuer_DER, Issuer, Resp,
                          At_Time, Allow_SHA1, Skew, R);
      Check (Name & " => " & Expect'Image, R = Expect);
      if R /= Expect then
         Put_Line ("   got " & R'Image);
      end if;
   end OCSP_Case;

   procedure CRL_Case
     (Name      : String;
      Leaf_File : String;
      CRL_File  : String;
      Expect    : Revocation_Result;
      At_Time   : X509.Date_Time := Now;
      Tamper    : Boolean := False;
      Issuer_File : String := "ca.der")
   is
      Leaf_DER   : constant X509.Byte_Seq := Load (Leaf_File);
      Issuer_DER : constant X509.Byte_Seq := Load (Issuer_File);
      CRL_DER    : X509.Byte_Seq := Load (CRL_File);
      Leaf, Issuer : X509.Certificate;
      V          : X509.CRL.CRL_View;
      OK1, OK2, OK3 : Boolean;
      R          : Revocation_Result;
   begin
      X509.Parse (Leaf_DER, Leaf, OK1);
      X509.Parse (Issuer_DER, Issuer, OK2);
      if Tamper then
         CRL_DER (CRL_DER'Last) := CRL_DER (CRL_DER'Last) xor 16#01#;
      end if;
      X509.CRL.Parse (CRL_DER, V, OK3);
      if not (OK1 and OK2 and OK3) then
         Check (Name & " (fixture parse)", False);
         return;
      end if;
      Check_CRL (Leaf_DER, Leaf, Issuer_DER, Issuer, CRL_DER, V, At_Time, Skew, R);
      Check (Name & " => " & Expect'Image, R = Expect);
      if R /= Expect then
         Put_Line ("   got " & R'Image);
      end if;
   end CRL_Case;

   --  Two CRLs in a store, in the given order (second may be "").
   procedure Store_Case
     (Name       : String;
      Leaf_File  : String;
      CRL_A      : String;
      CRL_B      : String;
      Expect     : Revocation_Result)
   is
      Leaf_DER   : constant X509.Byte_Seq := Load (Leaf_File);
      Issuer_DER : constant X509.Byte_Seq := Load ("ca.der");
      Leaf, Issuer : X509.Certificate;
      OK1, OK2, OK : Boolean;
      Store      : SPARKTLS.CRL_Store;
      R          : Revocation_Result;
   begin
      X509.Parse (Leaf_DER, Leaf, OK1);
      X509.Parse (Issuer_DER, Issuer, OK2);
      if not (OK1 and OK2) then
         Check (Name & " (fixture parse)", False);
         return;
      end if;
      Add_CRL (Store, new X509.Byte_Seq'(Load (CRL_A)), OK);
      if CRL_B /= "" then
         Add_CRL (Store, new X509.Byte_Seq'(Load (CRL_B)), OK);
      end if;
      declare
         --  No pool: the alternate-signer fallback (RFC 5280 6.3.3 f) has
         --  nothing to try, so these cases exercise the direct-issuer path.
         No_Ints  : constant SPARKTLS.Cert_Pool := (others => <>);
         No_Roots : constant SPARKTLS.Root_Pool := (others => <>);
      begin
         Check_CRLs (Leaf_DER, Leaf, Issuer_DER, Issuer, Store,
                     No_Ints, 0, No_Roots, 0, Now, Skew, R);
      end;
      Check (Name & " => " & Expect'Image, R = Expect);
      if R /= Expect then
         Put_Line ("   got " & R'Image);
      end if;
   end Store_Case;

   procedure Time_Cases is
      use type Interfaces.Unsigned_64;
   begin
      Check ("epoch", To_Seconds ((1970, 1, 1, 0, 0, 0)) = 0);
      Check ("2000-03-01", To_Seconds ((2000, 3, 1, 0, 0, 0)) = 951_868_800);
      Check ("2026-09-09T05:25:16Z", To_Seconds ((2026, 9, 9, 5, 25, 16)) = 1_788_931_516);
      Check ("window: inside", In_Window (Now, (2026, 9, 9, 0, 0, 0), True, (2026, 9, 16, 0, 0, 0), 0));
      Check ("window: before start", not In_Window ((2026, 9, 8, 0, 0, 0), (2026, 9, 9, 0, 0, 0), True, (2026, 9, 16, 0, 0, 0), 0));
      Check ("window: skew rescues start", In_Window ((2026, 9, 8, 23, 58, 0), (2026, 9, 9, 0, 0, 0), True, (2026, 9, 16, 0, 0, 0), 300));
      Check ("window: after end", not In_Window (Future, (2026, 9, 9, 0, 0, 0), True, (2026, 9, 16, 0, 0, 0), 300));
      Check ("window: no end", In_Window (Future, (2026, 9, 9, 0, 0, 0), False, (2026, 9, 16, 0, 0, 0), 0));
   end Time_Cases;

begin
   if not Ada.Directories.Exists (Dir & "/ca.der") then
      Put_Line ("SKIP: revocation fixtures not found in " & Dir
                & " (run sparkx509/tests/revocation/gen.sh)");
      return;
   end if;

   Time_Cases;

   --  OCSP
   OCSP_Case ("ocsp good, CA-signed, byName, SHA-1",      "good.der",    "ocsp_good_ca.der",           Rev_Ok);
   OCSP_Case ("ocsp good, CA-signed, byKey",              "good.der",    "ocsp_good_ca_keyid.der",     Rev_Ok);
   OCSP_Case ("ocsp revoked, CA-signed",                  "revoked.der", "ocsp_revoked_ca.der",        Rev_Revoked);
   OCSP_Case ("ocsp good, delegated responder",           "good.der",    "ocsp_good_delegated.der",    Rev_Ok);
   OCSP_Case ("ocsp revoked, delegated responder",        "revoked.der", "ocsp_revoked_delegated.der", Rev_Revoked);
   OCSP_Case ("ocsp good, SHA-256 CertID + nonce",        "good.der",    "ocsp_good_sha256_nonce.der", Rev_Ok);
   OCSP_Case ("ocsp SHA-1 CertID refused by policy",      "good.der",    "ocsp_good_ca.der",           Rev_Insufficient, Allow_SHA1 => False);
   OCSP_Case ("ocsp SHA-256 CertID unaffected by policy", "good.der",    "ocsp_good_sha256_nonce.der", Rev_Ok,           Allow_SHA1 => False);
   OCSP_Case ("ocsp response for the other leaf",         "revoked.der", "ocsp_good_ca.der",           Rev_Insufficient);
   OCSP_Case ("ocsp stale (past nextUpdate)",             "good.der",    "ocsp_good_ca.der",           Rev_Insufficient, At_Time => Future);
   OCSP_Case ("ocsp tampered",                            "good.der",    "ocsp_good_ca.der",           Rev_Malformed,    Tamper => True);
   OCSP_Case ("ocsp wrong issuer",                        "good.der",    "ocsp_good_ca.der",           Rev_Malformed,    Issuer_File => "ocsp.der");
   --  The delegate's own certificate offered as the "issuer": it did sign
   --  the response, but the CertID hashes name the real CA, so the
   --  response is not about a certificate this issuer issued.
   OCSP_Case ("ocsp signer ok but CertID names another issuer", "good.der", "ocsp_good_delegated.der", Rev_Insufficient, Issuer_File => "ocsp.der");

   --  CRL
   CRL_Case ("crl: good leaf not listed",     "good.der",    "crl.der",       Rev_Ok);
   CRL_Case ("crl: revoked leaf listed",      "revoked.der", "crl.der",       Rev_Revoked);
   CRL_Case ("crl: empty CRL",                "revoked.der", "crl_empty.der", Rev_Ok);
   CRL_Case ("crl: stale",                    "good.der",    "crl.der",       Rev_Insufficient, At_Time => Future);
   CRL_Case ("crl: tampered signature",       "good.der",    "crl.der",       Rev_Malformed,    Tamper => True);
   CRL_Case ("crl: foreign issuer",           "good.der",    "crl.der",       Rev_Insufficient, Issuer_File => "ocsp.der");

   --  Sharded CRLs (issuingDistributionPoint scoping, RFC 5280 6.3.3 b.2)
   CRL_Case ("shard: leaf1 listed in shard1",        "shard1.der", "crl_shard1.der", Rev_Revoked);
   CRL_Case ("shard: leaf2 listed in shard2",        "shard2.der", "crl_shard2.der", Rev_Revoked);
   CRL_Case ("shard: leaf1 vs shard2 = not covered", "shard1.der", "crl_shard2.der", Rev_Insufficient);
   CRL_Case ("shard: leaf2 vs shard1 = not covered", "shard2.der", "crl_shard1.der", Rev_Insufficient);
   CRL_Case ("shard: unscoped CRL still covers leaf1", "shard1.der", "crl.der",     Rev_Ok);
   Store_Case ("shard: store [shard2, shard1], leaf1 => revoked via shard1", "shard1.der",
               "crl_shard2.der", "crl_shard1.der", Rev_Revoked);
   Store_Case ("shard: store [shard1, shard2], leaf2 => revoked via shard2", "shard2.der",
               "crl_shard1.der", "crl_shard2.der", Rev_Revoked);
   Store_Case ("shard: store [shard2 only], leaf1 => no evidence", "shard1.der",
               "crl_shard2.der", "", Rev_Insufficient);

   Put_Line ("Revocation:" & Pass'Image & " passed," & Fail'Image & " failed");
end Test_Revocation;
