--  C-reference KAT test for SPARKTLSCrypto.Fiat_25519.
--
--  Mirrors test_fiat_p256_kat: loads vectors generated by the C dumper
--  (SPARKTLSCrypto/tools/dump_fiat_25519_kat_c.c) and runs each Fiat
--  Curve25519 op through the SPARK Ada port, asserting bit-identical
--  outputs against the upstream fiat-crypto C reference.

with Ada.Text_IO;          use Ada.Text_IO;
with Ada.Command_Line;
with Interfaces;           use Interfaces;
with SPARKNaCl;            use SPARKNaCl;
with SPARKTLSCrypto.Fiat_25519;
use  SPARKTLSCrypto.Fiat_25519;
with Fiat_25519_KAT_Data;

procedure Test_Fiat_25519_KAT is
   package KD renames Fiat_25519_KAT_Data;

   Total : Natural := 0;
   Fails : Natural := 0;

   procedure Check (Name : String; OK : Boolean) is
   begin
      Total := Total + 1;
      if not OK then
         Put_Line ("  FAIL: " & Name);
         Fails := Fails + 1;
      end if;
   end Check;

   procedure Show_Mismatch (Name : String; Idx : Natural; Got, Want : FE) is
   begin
      Put_Line ("    [" & Idx'Image & "] " & Name);
      Put_Line ("      got : "
                & Got (0)'Image & Got (1)'Image & Got (2)'Image
                & Got (3)'Image & Got (4)'Image);
      Put_Line ("      want: "
                & Want (0)'Image & Want (1)'Image & Want (2)'Image
                & Want (3)'Image & Want (4)'Image);
   end Show_Mismatch;

   R   : FE;
begin
   Put_Line ("--- Fiat 25519 vs C reference (" & KD.N_Vectors'Image
             & " vectors per op) ---");

   for I in 0 .. KD.N_Vectors - 1 loop
      R := Mul (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Mul", R = KD.Expect_Mul (I));
      if R /= KD.Expect_Mul (I) then Show_Mismatch ("Mul", I, R, KD.Expect_Mul (I)); end if;

      R := Sqr (KD.Inputs_A (I));
      Check ("Sqr", R = KD.Expect_Sqr (I));
      if R /= KD.Expect_Sqr (I) then Show_Mismatch ("Sqr", I, R, KD.Expect_Sqr (I)); end if;

      R := Add (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Add", R = KD.Expect_Add (I));
      if R /= KD.Expect_Add (I) then Show_Mismatch ("Add", I, R, KD.Expect_Add (I)); end if;

      R := Sub (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Sub", R = KD.Expect_Sub (I));
      if R /= KD.Expect_Sub (I) then Show_Mismatch ("Sub", I, R, KD.Expect_Sub (I)); end if;

      --  Carry mutates in place; copy first.
      R := KD.Inputs_A (I);
      Carry (R);
      Check ("Carry", R = KD.Expect_Carry (I));
      if R /= KD.Expect_Carry (I) then Show_Mismatch ("Carry", I, R, KD.Expect_Carry (I)); end if;

      --  To_Bytes / From_Bytes — these are NOT in our SPARK Fiat_25519 spec
      --  (they live in X25519/Ed25519 code that builds on the field). Skip
      --  for now; the C reference vectors are still useful documentation.
   end loop;

   New_Line;
   Put_Line ("Total checks:" & Total'Image
             & "  Failures:" & Fails'Image);
   if Fails > 0 then
      Ada.Command_Line.Set_Exit_Status (1);
   end if;
end Test_Fiat_25519_KAT;
