--  C-reference KAT test for SPARKTLSCrypto.Fiat_P256.
--
--  Loads vectors from Fiat_P256_KAT_Data (generated by the C dumper at
--  SPARKTLSCrypto/tools/dump_fiat_kat_c.c against fiat-crypto's own
--  p256_64.c), runs each operation through the SPARK Ada port, and
--  compares output bit-for-bit. Any mismatch => exit code 1.
--
--  Build: included in tests/unit/unit_tests.gpr.
--  Run:   ./bin/tests/test_fiat_p256_kat
--
--  Whenever the SPARK port changes (e.g., post-refactor), re-run.
--  No need to regenerate the data unless Fiat itself changes.

with Ada.Text_IO;          use Ada.Text_IO;
with Ada.Command_Line;
with Interfaces;           use Interfaces;
with SPARKNaCl;            use SPARKNaCl;
with SPARKTLSCrypto.Fiat_P256;
use  SPARKTLSCrypto.Fiat_P256;
with Fiat_P256_KAT_Data;

procedure Test_Fiat_P256_KAT is
   package KD renames Fiat_P256_KAT_Data;

   Total : Natural := 0;
   Fails : Natural := 0;

   procedure Check (Name : String; OK : Boolean) is
   begin
      Total := Total + 1;
      if not OK then
         Put_Line ("  FAIL: " & Name);
         Fails := Fails + 1;
      end if;
   end Check;

   procedure Show_Mismatch (Name : String; Idx : Natural; Got, Want : FE) is
   begin
      Put_Line ("    [" & Idx'Image & "] " & Name);
      Put_Line ("      got : "
                & Got (0)'Image & Got (1)'Image
                & Got (2)'Image & Got (3)'Image);
      Put_Line ("      want: "
                & Want (0)'Image & Want (1)'Image
                & Want (2)'Image & Want (3)'Image);
   end Show_Mismatch;

   R   : FE;
   RBs : Byte_Seq (0 .. 31);
begin
   Put_Line ("--- Fiat P-256 vs C reference (" & KD.N_Vectors'Image
             & " vectors per op) ---");

   for I in 0 .. KD.N_Vectors - 1 loop
      R := Mul (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Mul", R = KD.Expect_Mul (I));
      if R /= KD.Expect_Mul (I) then Show_Mismatch ("Mul", I, R, KD.Expect_Mul (I)); end if;

      R := Sqr (KD.Inputs_A (I));
      Check ("Sqr", R = KD.Expect_Sqr (I));
      if R /= KD.Expect_Sqr (I) then Show_Mismatch ("Sqr", I, R, KD.Expect_Sqr (I)); end if;

      R := Add (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Add", R = KD.Expect_Add (I));
      if R /= KD.Expect_Add (I) then Show_Mismatch ("Add", I, R, KD.Expect_Add (I)); end if;

      R := Sub (KD.Inputs_A (I), KD.Inputs_B (I));
      Check ("Sub", R = KD.Expect_Sub (I));
      if R /= KD.Expect_Sub (I) then Show_Mismatch ("Sub", I, R, KD.Expect_Sub (I)); end if;

      R := From_Montgomery (KD.Inputs_A (I));
      Check ("From_Montgomery", R = KD.Expect_From_Mont (I));
      if R /= KD.Expect_From_Mont (I) then Show_Mismatch ("From_Mont", I, R, KD.Expect_From_Mont (I)); end if;

      R := To_Montgomery (KD.Inputs_NM (I));
      Check ("To_Montgomery", R = KD.Expect_To_Mont (I));
      if R /= KD.Expect_To_Mont (I) then Show_Mismatch ("To_Mont", I, R, KD.Expect_To_Mont (I)); end if;

      To_Bytes (RBs, KD.Inputs_NM (I));
      declare
         OK : Boolean := True;
      begin
         for J in RBs'Range loop
            if RBs (J) /= KD.Expect_To_Bytes (I) (Integer (J)) then OK := False; end if;
         end loop;
         Check ("To_Bytes", OK);
      end;

      declare
         In_Bytes : Byte_Seq (0 .. 31);
      begin
         for J in In_Bytes'Range loop
            In_Bytes (J) := KD.FromBytes_Input (I) (Integer (J));
         end loop;
         R := From_Bytes (In_Bytes);
         Check ("From_Bytes", R = KD.Expect_From_Bytes (I));
         if R /= KD.Expect_From_Bytes (I) then Show_Mismatch ("From_Bytes", I, R, KD.Expect_From_Bytes (I)); end if;
      end;
   end loop;

   New_Line;
   Put_Line ("Total checks:" & Total'Image
             & "  Failures:" & Fails'Image);
   if Fails > 0 then
      Ada.Command_Line.Set_Exit_Status (1);
   end if;
end Test_Fiat_P256_KAT;
