#!/usr/bin/env python3
"""Summarise a TLS-Anvil output folder and diff it against a baseline.

Usage: summarize.py OUTPUT_DIR [--expected FILE] [--update-baseline]

Every test is keyed by "<TestClass>.<TestMethod>" (the random TestId
suffix changes between runs). The baseline lists the keys that are
expected to be FULLY_FAILED or PARTIALLY_FAILED, one per line, '#'
comments allowed. Exit status: 0 when the failures match the baseline,
1 on a regression (new failure) or when no test ran, 2 when the output
folder has no results at all.
"""
import glob, json, os, sys
from collections import Counter

def load(out_dir):
    tests = {}
    for f in glob.glob(os.path.join(out_dir, "results", "*", "_testRun.json")):
        try:
            with open(f) as fh:
                d = json.load(fh)
        except Exception:
            continue
        key = "%s.%s" % (str(d.get("TestClass", "?")).split(".")[-1], d.get("TestMethod", "?"))
        tests[key] = d
    return tests

def main(argv):
    if not argv:
        print(__doc__); return 2
    out_dir = argv[0]; expected = None; update = False
    i = 1
    while i < len(argv):
        if argv[i] == "--expected": expected = argv[i + 1]; i += 2
        elif argv[i] == "--update-baseline": update = True; i += 1
        else: print("unknown arg", argv[i]); return 2
    tests = load(out_dir)
    if not tests:
        print("=== TLS-Anvil: no results in %s ===" % out_dir); return 2
    counts = Counter(d.get("Result", "UNKNOWN") for d in tests.values())
    ran = sum(v for k, v in counts.items() if k != "DISABLED")
    failed = sorted(k for k, d in tests.items() if d.get("Result") in ("FULLY_FAILED", "PARTIALLY_FAILED"))
    passed = sum(v for k, v in counts.items() if k in ("STRICTLY_SUCCEEDED", "CONCEPTUALLY_SUCCEEDED"))
    print("=== TLS-Anvil: %d/%d passed, %d failed, %d disabled ===" % (passed, ran, len(failed), counts.get("DISABLED", 0)))
    for k in ("STRICTLY_SUCCEEDED", "CONCEPTUALLY_SUCCEEDED", "PARTIALLY_FAILED", "FULLY_FAILED", "DISABLED", "TEST_SUITE_ERROR"):
        if k in counts: print("    %-22s %d" % (k, counts[k]))
    if ran == 0:
        reasons = Counter(str(d.get("DisabledReason", "?")).split(":")[0] for d in tests.values())
        print("!!! FAILED RUN: every test was disabled. TLS-Scanner saw no usable features;")
        print("    check %s/tls-scanner.txt. Disabled reasons:" % out_dir)
        for r, n in reasons.most_common(6): print("      %4d  %s" % (n, r))
        return 1
    if update and expected:
        with open(expected, "w") as fh:
            fh.write("# TLS-Anvil expected failures, keyed <TestClass>.<TestMethod>. Regenerated by\n")
            fh.write("# tests/tlsanvil/run.sh --update-baseline; document every change in git.\n")
            for k in failed: fh.write(k + "\n")
        print("Baseline written: %d entries -> %s" % (len(failed), expected)); return 0
    baseline = set()
    if expected and os.path.exists(expected):
        with open(expected) as fh:
            baseline = {l.strip() for l in fh if l.strip() and not l.startswith("#")}
    new_fail = [k for k in failed if k not in baseline]
    new_pass = sorted(baseline - set(failed))
    for k in failed:
        d = tests[k]
        mark = "   " if k in baseline else "NEW"
        print("  %s %-18s %s" % (mark, d.get("Result"), k))
        reason = str(d.get("FailedReason", "") or "").strip().replace("\n", " ")
        if reason: print("        %s" % reason[:160])
    if not expected or not os.path.exists(expected):
        print("    (no EXPECTED_FAILURES.txt; every failure above counts as new)")
        return 1 if failed else 0
    if new_fail:
        print("!!! REGRESSION: %d test(s) newly failing:" % len(new_fail))
        for k in new_fail: print("    " + k)
    if new_pass:
        print(">>> %d test(s) newly passing (update the baseline):" % len(new_pass))
        for k in new_pass: print("    " + k)
        print("    Refresh with: tests/tlsanvil/run.sh --update-baseline")
    if not new_fail and not new_pass:
        print("    Failures match EXPECTED_FAILURES.txt exactly (%d known)." % len(failed))
    return 1 if new_fail else 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
